### PR TITLE
[BackUpPassword]: Handle Errors and Loading 

### LINKED ISSUE #2553: [Google console crash log] BackupPasswordViewModel.saveContentToUriResult
```
Exception java.lang.IllegalStateException:
    at com.vultisig.wallet.ui.models.BackupPasswordViewModel.saveContentToUriResult (BackupPasswordViewModel.java:164)
    at com.vultisig.wallet.ui.screens.BackupPasswordScreenKt$BackupPasswordScreen$2$1.invoke (BackupPasswordScreen.kt:32)
    at com.vultisig.wallet.ui.screens.BackupPasswordScreenKt$BackupPasswordScreen$2$1.invoke (BackupPasswordScreen.kt:32)
    at com.vultisig.wallet.ui.utils.file.RequestCreateDocumentKt.RequestCreateDocument$lambda$2$lambda$1 (RequestCreateDocument.kt:29)
    at androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1$1.invoke$lambda$0 (ActivityResultRegistry.kt:104)
    at androidx.activity.result.ActivityResultRegistry.register (ActivityResultRegistry.kt:177)
    at androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1$1.invoke (ActivityResultRegistry.kt:104)
    at androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1$1.invoke (ActivityResultRegistry.kt:102)
    at androidx.compose.runtime.DisposableEffectImpl.onRemembered (Effects.kt:83)
    at androidx.compose.runtime.internal.RememberEventDispatcher.dispatchRememberList (RememberEventDispatcher.kt:182)
    at androidx.compose.runtime.internal.RememberEventDispatcher.dispatchRememberObservers (RememberEventDispatcher.kt:174)
    at androidx.compose.runtime.CompositionImpl.applyChangesInLocked (Composition.kt:1044)
    at androidx.compose.runtime.CompositionImpl.applyChanges (Composition.kt:1067)
    at androidx.compose.runtime.Recomposer.composeInitial$runtime_release (Recomposer.kt:1159)
    at androidx.compose.runtime.CompositionImpl.composeInitial (Composition.kt:677)
    at androidx.compose.runtime.CompositionImpl.setContent (CompositionImpl.java:616)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke (WrappedComposition.java:123)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke (WrappedComposition.java:114)
    at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable (AndroidComposeView.android.kt:1959)
    at androidx.compose.ui.platform.WrappedComposition.setContent (Wrapper.android.kt:114)
    at androidx.compose.ui.platform.WrappedComposition.onStateChanged (Wrapper.android.kt:168)
    at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent (LifecycleRegistry.jvm.kt:320)
    at androidx.lifecycle.LifecycleRegistry.addObserver (LifecycleRegistry.jvm.kt:198)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke (WrappedComposition.java:121)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke (WrappedComposition.java:114)
    at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow (AndroidComposeView.android.kt:2038)
    at android.view.View.dispatchAttachedToWindow (View.java:20731)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3509)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3516)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3516)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3516)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3516)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3516)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3516)
    at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2730)
    at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:2257)
    at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:8796)
    at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1161)
    at android.view.Choreographer.doCallbacks (Choreographer.java:983)
    at android.view.Choreographer.doFrame (Choreographer.java:908)
    at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1146)
    at android.os.Handler.handleCallback (Handler.java:938)
    at android.os.Handler.dispatchMessage (Handler.java:99)
    at android.os.Looper.loop (Looper.java:263)
    at android.app.ActivityThread.main (ActivityThread.java:8292)
    at java.lang.reflect.Method.invoke
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:612)
    at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1006)

```

### PR DESCRIPTION
**Pull request by JaimeToca**
## Description

Please include a summary of the change and which issue is fixed. 

- Avoid throwing exceptions to the UI that leads to crash
- Introduce isLoading, to avoid conditions race

Fixes #2553

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved backup flow resilience with safer null handling, clearer user-facing errors, guarded navigation when vault data is unavailable, and deferring vault-dependent actions until vault is loaded.
  * Added error logging during backup encryption and route parsing to aid troubleshooting.

* **Chores**
  * Added a UI preview for the Backup Password screen to aid design and verification.

### CODE REVIEW

File: app/src/main/java/com/vultisig/wallet/ui/models/BackupPasswordViewModel.kt [hunk 1]
```diff
@@ -62,12 +65,18 @@ internal class BackupPasswordViewModel @Inject constructor(
...
+        null
+    }
 
-    private val vaultId = args.vaultId
-    private val vaultType = args.vaultType
+    private val vaultId = args?.vaultId
+    private val vaultType = args?.vaultType
 
     private val vault = MutableStateFlow<Vault?>(null)
+    private val isVaultLoaded = MutableStateFlow(false)
```
Comment (aminsato) [inline app/src/main/java/com/vultisig/wallet/ui/models/BackupPasswordViewModel.kt:79]: Can this be defined as a simple Boolean, or as a MutableStateFlow(false)?

**Review by johnnyluo — APPROVED** [review]
LGTM
