### PR TITLE
Fix getTransaction crash

### LINKED ISSUE #2511: [Google console crash logs] SwapTransactionRepositoryImpl$getTransaction$$inlined$map$1$2.emit
```
Exception java.lang.IllegalStateException:
    at com.vultisig.wallet.data.repositories.SwapTransactionRepositoryImpl$getTransaction$$inlined$map$1$2.emit (SwapTransactionRepositoryImpl.java:51)
    at kotlinx.coroutines.flow.StateFlowImpl.collect (StateFlow.kt:401)
    at com.vultisig.wallet.data.repositories.SwapTransactionRepositoryImpl$getTransaction$$inlined$map$1.collect (SwapTransactionRepositoryImpl.java:109)
    at kotlinx.coroutines.flow.FlowKt__ReduceKt.first (FlowKt__Reduce.kt:196)
    at kotlinx.coroutines.flow.FlowKt.first (Flow.kt:1)
    at com.vultisig.wallet.data.repositories.SwapTransactionRepositoryImpl.getTransaction (SwapTransactionRepositoryImpl.java:32)
    at com.vultisig.wallet.ui.models.keysign.KeysignShareViewModel$loadSwapTransaction$1.invokeSuspend (KeysignShareViewModel.kt:109)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:100)
    at kotlinx.coroutines.EventLoopImplBase.processNextEvent (EventLoop.common.kt:263)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking (BlockingCoroutine.java:95)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking (BuildersKt__Builders.kt:69)
    at kotlinx.coroutines.BuildersKt.runBlocking (Builders.kt:1)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default (BuildersKt__Builders.kt:47)
    at kotlinx.coroutines.BuildersKt.runBlocking$default (Builders.kt:1)
    at com.vultisig.wallet.ui.models.keysign.KeysignShareViewModel.loadSwapTransaction (KeysignShareViewModel.java:108)
    at com.vultisig.wallet.ui.screens.keysign.KeysignScreenKt.KeysignScreen (KeysignScreen.kt:44)
    at com.vultisig.wallet.ui.navigation.ComposableSingletons$NavGraphKt$lambda$-486699853$1.invoke (NavGraph.kt:552)
    at com.vultisig.wallet.ui.navigation.ComposableSingletons$NavGraphKt$lambda$-486699853$1.invoke (NavGraph.kt:550)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:142)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.navigation.compose.NavHostKt$NavHost$32$1.invoke (NavHost.kt:704)
    at androidx.navigation.compose.NavHostKt$NavHost$32$1.invoke (NavHost.kt:703)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:384)
    at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider (SaveableStateHolder.kt:79)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider (NavBackStackEntryProvider.kt:65)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider (NavBackStackEntryProvider.kt:1)
    at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke (NavBackStackEntryProvider.kt:52)
    at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke (NavBackStackEntryProvider.kt:51)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:364)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider (NavBackStackEntryProvider.kt:47)
    at androidx.navigation.compose.NavHostKt$NavHost$32.invoke (NavHost.kt:703)
    at androidx.navigation.compose.NavHostKt$NavHost$32.invoke (NavHost.kt:683)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:142)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke (AnimatedContent.kt:862)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke (AnimatedContent.kt:852)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:130)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl (AnimatedVisibility.kt:755)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke (AnimatedContent.kt:834)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke (AnimatedContent.kt:817)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedContentKt.AnimatedContent (AnimatedContent.kt:872)
    at androidx.navigation.compose.NavHostKt.NavHost (NavHost.kt:655)
    at androidx.navigation.compose.NavHostKt.NavHost (NavHost.kt:212)
    at com.vultisig.wallet.ui.navigation.NavGraphKt.SetupNavGraph (NavGraph.kt:109)
    at com.vultisig.wallet.app.activity.MainActivity$onCreate$3$1.invoke (MainActivity.kt:100)
    at com.vultisig.wallet.app.activity.MainActivity$onCreate$3$1.invoke (MainActivity.kt:82)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:384)
    at androidx.compose.material3.TextKt.ProvideTextStyle (Text.kt:349)
    at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke (MaterialTheme.kt:69)
    at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke (MaterialTheme.kt:68)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:364)
    at androidx.compose.material3.MaterialThemeKt.MaterialTheme (MaterialTheme.kt:60)
    at com.vultisig.wallet.ui.theme.ThemeKt$OnBoardingComposeTheme$1.invoke (Theme.kt:23)
    at com.vultisig.wallet.ui.theme.ThemeKt$OnBoardingComposeTheme$1.invoke (Theme.kt:22)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at com.vultisig.wallet.ui.theme.AppUtilsKt$AppUtils$1.invoke (AppUtils.kt:35)
    at com.vultisig.wallet.ui.theme.AppUtilsKt$AppUtils$1.invoke (AppUtils.kt:34)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:364)
    at com.vultisig.wallet.ui.theme.AppUtilsKt.AppUtils (AppUtils.kt:29)
    at com.vultisig.wallet.ui.theme.ThemeKt.OnBoardingComposeTheme (Theme.kt:17)
    at com.vultisig.wallet.app.activity.MainActivity$onCreate$3.invoke (MainActivity.java:82)
    at com.vultisig.wallet.app.activity.MainActivity$onCreate$3.invoke (MainActivity.java:81)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.ui.platform.ComposeView.Content (ComposeView.android.kt:431)
    at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke (AbstractComposeView.java:250)
    at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke (AbstractComposeView.java:250)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:364)
    at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals (CompositionLocals.kt:216)
    at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke (AndroidCompositionLocals_android.kt:122)
    at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke (AndroidCompositionLocals_android.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:364)
    at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals (AndroidCompositionLocals.android.kt:110)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke (Wrapper.android.kt:140)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke (Wrapper.android.kt:139)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:384)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke (WrappedComposition.java:139)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke (WrappedComposition.java:123)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.internal.Utils_jvmKt.invokeComposable (Utils_jvm.kt:27)
    at androidx.compose.runtime.ComposerImpl.doCompose-aFTiNEg (Composer.kt:3694)
    at androidx.compose.runtime.ComposerImpl.composeContent--ZbOJvo$runtime_release (ComposerImpl.java:3616)
    at androidx.compose.runtime.CompositionImpl.composeContent (Composition.kt:792)
    at androidx.compose.runtime.Recomposer.composeInitial$runtime_release (Recomposer.kt:1132)
    at androidx.compose.runtime.CompositionImpl.composeInitial (Composition.kt:677)
    at androidx.compose.runtime.CompositionImpl.setContent (CompositionImpl.java:616)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke (WrappedComposition.java:123)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke (WrappedComposition.java:114)
    at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable (AndroidComposeView.android.kt:1959)
    at androidx.compose.ui.platform.WrappedComposition.setContent (Wrapper.android.kt:114)
    at androidx.compose.ui.platform.WrappedComposition.onStateChanged (Wrapper.android.kt:168)
    at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent (LifecycleRegistry.jvm.kt:320)
    at androidx.lifecycle.LifecycleRegistry.addObserver (LifecycleRegistry.jvm.kt:198)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke (WrappedComposition.java:121)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke (WrappedComposition.java:114)
    at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow (AndroidComposeView.android.kt:2038)
    at android.view.View.dispatchAttachedToWindow (View.java:22581)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3731)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3740)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3740)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3740)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3740)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3740)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3740)
    at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:3704)
    at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:3151)
    at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:11068)
    at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1321)
    at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1329)
    at android.view.Choreographer.doCallbacks (Choreographer.java:930)
    at android.view.Choreographer.doFrame (Choreographer.java:859)
    at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1303)
    at android.os.Handler.handleCallback (Handler.java:942)
    at android.os.Handler.dispatchMessage (Handler.java:99)
    at android.os.Looper.loopOnce (Looper.java:226)
    at android.os.Looper.loop (Looper.java:313)
    at android.app.ActivityThread.main (ActivityThread.java:8810)
    at java.lang.reflect.Method.invoke
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:604)
    at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)

```

### PR DESCRIPTION
**Pull request by aminsato**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #2511

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **Refactor**
  * Improved how transactions are retrieved and processed, streamlining verification and signing flows for more consistent behavior.
* **Bug Fixes**
  * Fixed sequencing so fee calculations and security scans run at the correct time and show clearer "Security scan failed" messages.
* **UX**
  * More reliable load-and-back navigation on failure and more deterministic UI state during transaction review.

### CODE REVIEW

**Comment by JaimeToca** [comment]
@aminsato why can't we just handle the error instead? this approach triggers side effects

**Comment by aminsato** [comment]
> @aminsato why can't we just handle the error instead? this approach triggers side effects

@JaimeToca 
We had a similar issue in the past with custom messages and solved it the same way (pr #2350
 issue #2337) and it didn't happen again.
What side effect do you mean and in what scenario could it happen?

File: app/src/main/java/com/vultisig/wallet/ui/models/VerifyTransactionViewModel.kt [hunk 1]
```diff
@@ -129,11 +125,10 @@ internal class VerifyTransactionViewModel @Inject constructor(
         loadFastSign()
         loadTransaction()
         loadPassword()
```
Comment (aminsato) [inline app/src/main/java/com/vultisig/wallet/ui/models/VerifyTransactionViewModel.kt]:
```
 init {
        loadFastSign()
        loadTransaction()
        loadPassword()
        scanTransaction()
    }
```
The problem with this initialization pattern is lack of proper error handling and coordination between asynchronous operations.

- Race conditions: All four methods launch coroutines independently without coordination. For example, tryToFastSignWithPassword() depends on password.value being loaded, but there's no guarantee loadPassword() completes first.

- No error propagation: If any of these operations fail (e.g., network error in loadTransaction()), the ViewModel continues with partial/invalid state.

- Uncontrolled concurrency: Multiple coroutines update uiState simultaneously without synchronization, potentially causing inconsistent UI states.

- No cancellation handling: If the ViewModel is cleared while these operations are running, they continue executing unnecessarily.

**Comment by johnnyluo** [comment]
@aminsato , please attach tx link here

**Review by JaimeToca — APPROVED** [review]
