### PR TITLE
Convert loadTransaction functions to be suspend functions

### LINKED ISSUE #2246: [Google console log] getTransaction$$inlined$map$1$2.emit
**Describe the bug**
`Exception java.lang.IllegalStateException:
    at com.vultisig.wallet.data.repositories.TransactionRepositoryImpl$getTransaction$$inlined$map$1$2.emit (TransactionRepositoryImpl.java:51)
    at kotlinx.coroutines.flow.StateFlowImpl.collect (StateFlow.kt:401)
    at com.vultisig.wallet.data.repositories.TransactionRepositoryImpl$getTransaction$$inlined$map$1.collect (TransactionRepositoryImpl.java:109)
    at kotlinx.coroutines.flow.FlowKt__ReduceKt.first (FlowKt__Reduce.kt:196)
    at kotlinx.coroutines.flow.FlowKt.first (Flow.kt:1)
    at com.vultisig.wallet.ui.models.keysign.KeysignShareViewModel$loadTransaction$1.invokeSuspend (KeysignShareViewModel.kt:68)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:100)
    at kotlinx.coroutines.EventLoopImplBase.processNextEvent (EventLoop.common.kt:263)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking (BlockingCoroutine.java:95)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking (BuildersKt__Builders.kt:69)
    at kotlinx.coroutines.BuildersKt.runBlocking (Builders.kt:1)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default (BuildersKt__Builders.kt:47)
    at kotlinx.coroutines.BuildersKt.runBlocking$default (Builders.kt:1)
    at com.vultisig.wallet.ui.models.keysign.KeysignShareViewModel.loadTransaction (KeysignShareViewModel.java:67)
    at com.vultisig.wallet.ui.screens.keysign.KeysignScreenKt.KeysignScreen (KeysignScreen.kt:35)
    at com.vultisig.wallet.ui.navigation.ComposableSingletons$NavGraphKt$lambda$-1056971659$1.invoke (NavGraph.kt:529)
    at com.vultisig.wallet.ui.navigation.ComposableSingletons$NavGraphKt$lambda$-1056971659$1.invoke (NavGraph.kt:527)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:142)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.navigation.compose.NavHostKt$NavHost$32$1.invoke (NavHost.kt:704)
    at androidx.navigation.compose.NavHostKt$NavHost$32$1.invoke (NavHost.kt:703)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:384)
    at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider (SaveableStateHolder.kt:79)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider (NavBackStackEntryProvider.kt:65)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider (NavBackStackEntryProvider.kt:1)
    at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke (NavBackStackEntryProvider.kt:52)
    at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke (NavBackStackEntryProvider.kt:51)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:364)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider (NavBackStackEntryProvider.kt:47)
    at androidx.navigation.compose.NavHostKt$NavHost$32.invoke (NavHost.kt:703)
    at androidx.navigation.compose.NavHostKt$NavHost$32.invoke (NavHost.kt:683)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:142)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke (AnimatedContent.kt:862)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke (AnimatedContent.kt:852)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:130)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl (AnimatedVisibility.kt:755)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke (AnimatedContent.kt:834)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke (AnimatedContent.kt:817)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedContentKt.AnimatedContent (AnimatedContent.kt:872)
    at androidx.navigation.compose.NavHostKt.NavHost (NavHost.kt:655)
    at androidx.navigation.compose.NavHostKt.NavHost (NavHost.kt:212)
    at com.vultisig.wallet.ui.navigation.NavGraphKt.SetupNavGraph (NavGraph.kt:98)
    at com.vultisig.wallet.app.activity.MainActivity$onCreate$3$1.invoke (MainActivity.kt:100)
    at com.vultisig.wallet.app.activity.MainActivity$onCreate$3$1.invoke (MainActivity.kt:78)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:384)
    at androidx.compose.material3.TextKt.ProvideTextStyle (Text.kt:349)
    at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke (MaterialTheme.kt:69)
    at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke (MaterialTheme.kt:68)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:364)
    at androidx.compose.material3.MaterialThemeKt.MaterialTheme (MaterialTheme.kt:60)
    at com.vultisig.wallet.ui.theme.ThemeKt$OnBoardingComposeTheme$1.invoke (Theme.kt:21)
    at com.vultisig.wallet.ui.theme.ThemeKt$OnBoardingComposeTheme$1.invoke (Theme.kt:20)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at com.vultisig.wallet.ui.theme.AppUtilsKt$AppUtils$1.invoke (AppUtils.kt:35)
    at com.vultisig.wallet.ui.theme.AppUtilsKt$AppUtils$1.invoke (AppUtils.kt:34)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:364)
    at com.vultisig.wallet.ui.theme.AppUtilsKt.AppUtils (AppUtils.kt:29)
    at com.vultisig.wallet.ui.theme.ThemeKt.OnBoardingComposeTheme (Theme.kt:15)
    at com.vultisig.wallet.app.activity.MainActivity$onCreate$3.invoke (MainActivity.java:78)
    at com.vultisig.wallet.app.activity.MainActivity$onCreate$3.invoke (MainActivity.java:77)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.ui.platform.ComposeView.Content (ComposeView.android.kt:431)
    at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke (AbstractComposeView.java:250)
    at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke (AbstractComposeView.java:250)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:364)
    at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals (CompositionLocals.kt:216)
    at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke (AndroidCompositionLocals_android.kt:122)
    at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke (AndroidCompositionLocals_android.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:364)
    at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals (AndroidCompositionLocals.android.kt:110)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke (Wrapper.android.kt:140)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke (Wrapper.android.kt:139)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:384)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke (WrappedComposition.java:139)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke (WrappedComposition.java:123)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.internal.Utils_jvmKt.invokeComposable (Utils_jvm.kt:27)
    at androidx.compose.runtime.ComposerImpl.doCompose-aFTiNEg (Composer.kt:3694)
    at androidx.compose.runtime.ComposerImpl.composeContent--ZbOJvo$runtime_release (ComposerImpl.java:3616)
    at androidx.compose.runtime.CompositionImpl.composeContent (Composition.kt:792)
    at androidx.compose.runtime.Recomposer.composeInitial$runtime_release (Recomposer.kt:1132)
    at androidx.compose.runtime.CompositionImpl.composeInitial (Composition.kt:677)
    at androidx.compose.runtime.CompositionImpl.setContent (CompositionImpl.java:616)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke (WrappedComposition.java:123)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke (WrappedComposition.java:114)
    at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable (AndroidComposeView.android.kt:1959)
    at androidx.compose.ui.platform.WrappedComposition.setContent (Wrapper.android.kt:114)
    at androidx.compose.ui.platform.WrappedComposition.onStateChanged (Wrapper.android.kt:168)
    at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent (LifecycleRegistry.jvm.kt:320)
    at androidx.lifecycle.LifecycleRegistry.addObserver (LifecycleRegistry.jvm.kt:198)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke (WrappedComposition.java:121)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke (WrappedComposition.java:114)
    at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow (AndroidComposeView.android.kt:2038)
    at android.view.View.dispatchAttachedToWindow (View.java:24135)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3714)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3721)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3721)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3721)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3721)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3721)
    at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3721)
    at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:4313)
    at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:3701)
    at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:12533)
    at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1751)
    at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1760)
    at android.view.Choreographer.doCallbacks (Choreographer.java:1216)
    at android.view.Choreographer.doFrame (Choreographer.java:1142)
    at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1707)
    at android.os.Handler.handleCallback (Handler.java:959)
    at android.os.Handler.dispatchMessage (Handler.java:100)
    at android.os.Looper.loopOnce (Looper.java:257)
    at android.os.Looper.loop (Looper.java:342)
    at android.app.ActivityThread.main (ActivityThread.java:9579)
    at java.lang.reflect.Method.invoke
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:619)
    at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:929)
`
**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel]

**Additional context**

### PR DESCRIPTION
**Pull request by aminsato**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #2246

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **Refactor**
  * Improved transaction loading responsiveness by introducing asynchronous loading with visible loading indicators.
  * Enhanced user experience by showing a loading spinner while transaction data is being fetched.
  * Optimized transaction data fetching to occur only when relevant transaction type or ID changes.

### CODE REVIEW

File: app/src/main/java/com/vultisig/wallet/ui/screens/keysign/KeysignScreen.kt [hunk 1]
```diff
@@ -31,11 +31,16 @@ internal fun KeysignScreen(
     keysignShareViewModel: KeysignShareViewModel =
         hiltViewModel(LocalActivity.current as MainActivity)
 ) {
-    when (txType) {
-        Send -> keysignShareViewModel.loadTransaction(transactionId)
-        Swap -> keysignShareViewModel.loadSwapTransaction(transactionId)
-        Deposit -> keysignShareViewModel.loadDepositTransaction(transactionId)
-        Sign -> keysignShareViewModel.loadSignMessageTx(transactionId)
+    LaunchedEffect(
```
Comment (johnnyluo) [inline app/src/main/java/com/vultisig/wallet/ui/screens/keysign/KeysignScreen.kt:34]: @aminsato , I believe this cause problems , we have to wait for the `LaunchedEffect` to finish before we show the keysign screen , otherwise the app will present stale data , for example , the first time trying to send, it will present an error screen say keysignpayload is not available , the second send might present QR of previous keysign message

**Review by johnnyluo — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/vultisig/wallet/ui/screens/keysign/KeysignScreen.kt (hunk 1 above)
Comment (aminsato) [reply app/src/main/java/com/vultisig/wallet/ui/screens/keysign/KeysignScreen.kt]: @johnnyluo @JaimeToca 
Actually, using runBlocking blocks the UI thread, which can cause unintended side effects. Instead, we're using LaunchedEffect to launch a separate coroutine and avoid blocking the UI:
🔗 https://developer.android.com/develop/ui/compose/side-effects

I’ve updated the PR to include a loading check, so it now waits for loadDepositTransaction to complete before proceeding.

**Review by johnnyluo — APPROVED** [review]
LGTM
