### PR TITLE
Remove max button from swap screen

### LINKED ISSUE #2351: [BUG] - "Insufficient Funds" Error for All Token Swaps from ARB on Arbitrum chain
**Summary:**
On Android v1.0.69 any attempt to swap ARB to any token on Arbitrum fails with an *"Insufficient Funds"* error, even when the wallet has enough balance to cover both the swap amount and gas fees. This blocks all swap operations from ARB network tokens.

image

### PR DESCRIPTION
**Pull request by aminsato**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #2351

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **UI**
  * Simplified the swap percentage picker by removing the MAX option.
  * Quick-select options now include 25%, 50%, and 75% only.
  * Balanced three-button layout improves clarity and reduces the chance of unintentionally selecting the full balance.

### CODE REVIEW

**Review by johnnyluo — APPROVED** [review]
LGTM

File: app/src/main/java/com/vultisig/wallet/ui/screens/swap/SwapScreen.kt [hunk 1]
```diff
@@ -429,12 +429,6 @@ internal fun SwapScreen(
                                     onSelectSrcPercentage(0.75f)
                                 },
                             )
-                            PercentageItem(
-                                title = "MAX",
-                                onClick = {
-                                    onSelectSrcPercentage(1f)
-                                },
-                            )
```
Comment (JaimeToca) [inline app/src/main/java/com/vultisig/wallet/ui/screens/swap/SwapScreen.kt:437]: we should only remove for native coins @aminsato . It is completely fine to have it for tokens

Comment (johnnyluo) [reply app/src/main/java/com/vultisig/wallet/ui/screens/swap/SwapScreen.kt:437]: Let's keep it consistent , currently IOS / windows all removed the max button
