### PR TITLE
fix: handle server-side custom payload ID in keysign join flow

### LINKED ISSUE #3194: [BUG] Trying to sign too big payload with `eth_signTypedData_v4` method cash aplication
**Describe the bug**

When attempting to sign a very large payload using the eth_signTypedData_v4 method, the application closes.

**To Reproduce**
1. Go to https://community-tools-tau.vercel.app
2. Click on Ethereum -> request -> (dropdown) eth_signTypedData_v4
3. Insert your address and try to sign the default payload
4. Scan QR from android device
5. The Android app closes unexpectedly.

**Expected behavior**

The signing is successfully completed.

**Screenshots**

**Smartphone (please complete the following information):**

 - Version 1.0.95

**Additional context**

Maybe t has more to do with the management of the custom_id field than with the eth_signTypedData_v4 method, because smaller payloads do seem to be signed correctly using this method. Context: https://github.com/vultisig/vultisig-windows/pull/3149

### LINKED ISSUE #3284: [BUG] Mobile app crashes on signBytes sessions - "Keysign payload is null"
## Description

When using `vault.signBytes()` from the SDK with a SecureVault, the mobile app crashes when scanning the QR code.

## Root Cause

The SDK's `signBytesWithRelay()` in `RelaySigningService.ts` generates a QR payload **without** a `keysignPayload`:

```typescript
const qrPayload = await this.generateQRPayload({
    sessionId,
    hexEncryptionKey,
    localPartyId,
    vaultPublicKeyEcdsa: vault.publicKeys.ecdsa,
    // keysignPayload is NOT passed for signBytes
});
```

The Android app's `KeysignViewModel.kt` has a hard null check at the start of `startKeysignDkls()`:

```kotlin
if (keysignPayload == null && customMessagePayload == null) {
    error("Keysign payload is null")
}
```

Since the QR contains no payload data, both `keysignPayload` and `customMessagePayload` are null, and the app crashes.

## Steps to Reproduce

1. Create a SecureVault (2-of-2)
2. Load one share in the SDK (browser)
3. Call `vault.signBytes({ data: someHash, chain: Chain.Ethereum }, { onQRCodeReady: ... })`
4. QR code appears in the browser
5. Scan QR with the Vultisig mobile app
6. **Mobile app crashes** with "Keysign payload is null"

Before the crash, the mobile app briefly shows stale transaction data from a previous session (e.g., "send 0 WEWE on Base").

## Expected Behaviour

The mobile app should support `signBytes` sessions by:
- Accepting sessions without a `keysignPayload` when raw bytes are being signed
- Displaying a "Sign raw bytes" or "Sign message" UI instead of transaction details
- Using `CustomMessagePayload` or a new payload type for signBytes sessions

## Environment

- SDK version: latest (@vultisig/sdk)
- Android app: latest from Play Store
- Browser: Chrome 130+
- Vault type: SecureVault (2-of-2)

## Additional Context

The SDK documentation explicitly supports `signBytes()` for both FastVault and SecureVault (https://docs.vultisig.com/developer-docs/vultisig-sdk/sdk-users-guide#signing-arbitrary-bytes), but the mobile app's receiving side doesn't handle it.

The CLI (`clients/cli/src/commands/sign.ts`) also uses `signBytes` and would hit the same issue with SecureVaults.

### PR DESCRIPTION
**Pull request by johnnyluo**
When the SDK uses signBytes() with a relay vault, it stores the CustomMessagePayload on the relay server and sets custom_payload_id in the QR KeysignMessage proto (field 9). The app only handled the inline custom_message_payload (field 8), so both payloads were null and crashed with "Keysign payload is null".

Adds fetching of CustomMessagePayload by customPayloadId from the relay server in both the Vultisig relay and LAN NSD discovery paths, mirroring the existing payloadId pattern for keysign payloads.

Fixes #3284 
Fixes #3194 

## Description

Please include a summary of the change and which issue is fixed. 

Fixes #<issue-number>

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Agent Metadata (if applicable)
- **Agent**: 
- **Issue**: 
- **Confidence**: 
- **Needs human review for**: 

## Summary by CodeRabbit

* **New Features**
  * Keysign flow now supports server-hosted custom payloads referenced by payload IDs discovered in QR scans, links, or relay flows.
  * App can fetch, decode, and apply server-stored signing payloads when a payload ID is present so joining proceeds with server-provided data.

* **Bug Fixes**
  * Improved error handling and state transitions when server payloads are invalid, missing, or fail to apply, preserving existing QR-based flows.

### CODE REVIEW

File: app/src/main/java/com/vultisig/wallet/ui/models/keysign/JoinKeysignViewModel.kt [hunk 1]
```diff
@@ -1046,6 +1069,19 @@ constructor(
                     }
                 }
             }
+        } else if (customPayloadId.isNotEmpty() && tempKeysignMessageProto != null) {
+            viewModelScope.launch {
```
Comment (aminsato) [inline app/src/main/java/com/vultisig/wallet/ui/models/keysign/JoinKeysignViewModel.kt]: Please use use safeLaunch
