### PR TITLE
Fix using MAYAChain functions

### LINKED ISSUE #1997: [BUG] Unable to use MAYAChain functions
**Describe the bug**
It is impossible to use any MAYAChain functions.

**To Reproduce**
1. Go to MayaChain
2. Select functions
3. Try to sign

**Expected behavior**
Able to use functions without issues

**Screenshots**

Image

**Smartphone (please complete the following information):**
 - Version 57

### PR DESCRIPTION
**Pull request by aminsato**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #1997

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

- **Bug Fixes**
  - Ensured that the selected token is automatically set to the native token when loading address data in the deposit form. This improves accuracy and consistency in the displayed token selection.

### CODE REVIEW

File: app/src/main/java/com/vultisig/wallet/ui/models/deposit/DepositFormViewModel.kt [hunk 1]
```diff
@@ -663,7 +663,9 @@ internal class DepositFormViewModel @Inject constructor(
         val address = address.value ?: return null
         val userSelectedToken = state.value.selectedToken
         return address.accounts
-            .first { it.token.id == userSelectedToken.id }
+            .firstOrNull { it.token.id == userSelectedToken.id }
+            ?: address.accounts.firstOrNull { it.token.ticker.equals("MAYA", ignoreCase = true) }
```
Comment (johnnyluo) [inline app/src/main/java/com/vultisig/wallet/ui/models/deposit/DepositFormViewModel.kt:667]: I don't think this is right @aminsato , function on MayaChain mostly is using `CACAO`

Comment (aminsato) [reply app/src/main/java/com/vultisig/wallet/ui/models/deposit/DepositFormViewModel.kt]: Changed
