### PR TITLE
Fix the 4-digit code verification error in Fast Vault

### LINKED ISSUE #2051: [BUG] Prod - 4-digit code error message hidden by keypad on Samsung S23
**Labels:** Android, Samsung S23, UI, Error Message, Layout, Overlap, Keypad, Screen Size

**Description:**

On Samsung S23 devices, the error message on the "Enter the 4-digit code we emailed you" screen is displayed, but it is partially obscured by the keypad. This is because the screen size is too small or the layout is not optimized, causing the error message to overlap with the keypad. As a result, users cannot fully see the error message, making it difficult to understand the issue and correct their entry.

**Steps to Reproduce:**

1.  Open the application on a Samsung S23 device.
2.  Navigate to the "Enter the 4-digit code we emailed you" screen.
3.  Enter an incorrect 4-digit code.
4.  Observe whether the error message is fully visible, and if it overlaps with the keypad.

**Expected Result:**

When an incorrect code is entered, the error message should be fully visible on the screen without any overlap with the keypad or other UI elements. The layout should adapt to different screen sizes to ensure that all UI elements are displayed correctly.

**Actual Result:**

On Samsung S23 devices, the error message is partially or fully obscured by the keypad, preventing the user from fully reading the message.

**Environment:**

*   Platform: Android
*   Device: Samsung S23
*   Screen: Enter 4-digit code screen

**Attachments:**

Image

### PR DESCRIPTION
**Pull request by aminsato**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #2051

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **New Features**
  * Improved detection of on-screen keyboard visibility for smoother user experience across relevant screens.

* **Enhancements**
  * FastVaultVerificationScreen now scrolls automatically and adjusts layout when the keyboard is open, making code entry easier.
  * Paste button in FastVaultVerificationScreen is more visually responsive and accessible based on clipboard content.
  * UI spacing and feedback during code verification are clearer and more streamlined.

* **Refactor**
  * SwapScreen now uses an improved method for detecting keyboard visibility, ensuring consistent behavior.

### CODE REVIEW

File: app/src/main/java/com/vultisig/wallet/ui/components/KeyboardUtils.kt [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+ * @param onKeyboardIsClose Callback invoked when the keyboard becomes fully hidden.
+ */
+@Composable
+internal fun KeyboardDetector(
+    onKeyboardIsOpen: () -> Unit,
+    onKeyboardIsClose: () -> Unit = {},
+) {
+    val view = LocalView.current
+    val viewTreeObserver = view.viewTreeObserver
+    DisposableEffect(viewTreeObserver) {
```
Comment (JaimeToca) [inline app/src/main/java/com/vultisig/wallet/ui/components/KeyboardUtils.kt:36]: LGTM

maybe worth checking if view isAttachedToWindow() and exit with return
