### PR TITLE
Fix Polygon swap joining  from windows

### LINKED ISSUE #2321: [BUG] - **Polygon intra-chain swap fails with “signing error. signature is empty” on Android, timeout on Windows**
**Summary:**
In Windows Secure Vault, intra-chain swap on **Polygon** from **FOX** to **AVAX** fails.
* On **Android**: Error message — *"signing error. signature is empty. please try again"*
* On **Windows**: Error message — *"exited inbound processing due to a timeout after 1 min. signing error. please try again"*

### **Steps to Reproduce:**
1. Open **Secure Vault** (Windowsv1.0.34)
2. Select **Swap** From: `Polygon → FOX` To: `Polygon → AVAX`
5. Amount: **100% / Max**
6. Proceed with signing

**Android SS**
image

**Windows SS**
image

### PR DESCRIPTION
**Pull request by aminsato**
## Description

https://polygonscan.com/tx/0xa054db63daf73dd30d9b1691256244510f0025a49c461030d2e9b6b0cf2734f1

Joining BSC has the same issue because gasPrice from the payload is non-zero, while gas from the payload is null or zero

Fixes #2321

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

- Bug Fixes
  - Enforced required destination address in deposit and IBC transfer flows with a clear error when empty.
  - Improved gas fee handling on EVM networks (including BSC) to correctly apply user-provided values and fallbacks.

- Localization
  - Added translations for the destination address error message in EN, DE, ES, HR, IT, NL, PT, and RU.

### CODE REVIEW

File: data/src/main/kotlin/com/vultisig/wallet/data/chains/helpers/EthereumGasHelper.kt [hunk 1]
```diff
@@ -29,7 +29,7 @@ object EthereumGasHelper {
         if (keysignPayload.coin.chain == Chain.BscChain) {
             signingInputBuilder.apply {
                 txMode = Ethereum.TransactionMode.Legacy
-                if (gas.toLong() != EvmHelper.DEFAULT_ETH_SWAP_GAS_UNIT && gasPrice != BigInteger.ZERO) {
+                if (gas.toLong() != EvmHelper.DEFAULT_ETH_SWAP_GAS_UNIT || gasPrice != BigInteger.ZERO) {
```
Comment (johnnyluo) [inline data/src/main/kotlin/com/vultisig/wallet/data/chains/helpers/EthereumGasHelper.kt:32]: In this case  , what if gasPrice is 0 , this will cause issues

Comment (JaimeToca) [reply data/src/main/kotlin/com/vultisig/wallet/data/chains/helpers/EthereumGasHelper.kt:32]: @aminsato what about iOS, would this cause any issue?

If you have specific case, we can add json and test

Comment (aminsato) [reply data/src/main/kotlin/com/vultisig/wallet/data/chains/helpers/EthereumGasHelper.kt:32]: Yup
How can add json and test? enlighten me

Comment (aminsato) [reply data/src/main/kotlin/com/vultisig/wallet/data/chains/helpers/EthereumGasHelper.kt]: @JaimeToca 
Found the problem 
The issue was  that gas value  comming from the  palyload sometimes equals `EvmHelper.DEFAULT_ETH_SWAP_GAS_UNIT` which cause the condition  `if (gas.toLong() != EvmHelper.DEFAULT_ETH_SWAP_GAS_UNIT && gasPrice != BigInteger.ZERO)  ` to evaluate  false
Al cross-platform swaps have been testd, including swap between two Android devices

File: data/src/main/kotlin/com/vultisig/wallet/data/chains/helpers/EthereumGasHelper.kt [hunk 2]
```diff
@@ -29,7 +29,7 @@ object EthereumGasHelper {
         if (keysignPayload.coin.chain == Chain.BscChain) {
             signingInputBuilder.apply {
                 txMode = Ethereum.TransactionMode.Legacy
-                if (gas.toLong() != EvmHelper.DEFAULT_ETH_SWAP_GAS_UNIT && gasPrice != BigInteger.ZERO) {
+                if (gas != null && gasPrice != null) {
```
Comment (johnnyluo) [inline data/src/main/kotlin/com/vultisig/wallet/data/chains/helpers/EthereumGasHelper.kt:32]: I think here , all we need to ensure is , if gas is not zero/null , and gasPrice is not zero / null , then we just set it 

we shall net compare gas to EvmHelper.DEFAULT_ETH_SWAP_GAS_UNIT

Comment (aminsato) [reply data/src/main/kotlin/com/vultisig/wallet/data/chains/helpers/EthereumGasHelper.kt]: Done

File: data/src/main/kotlin/com/vultisig/wallet/data/api/swapAggregators/KyberSwap.kt [hunk 3]
```diff
@@ -74,9 +74,8 @@ class KyberSwap(
                     ).setData(quote.tx.data.removePrefix("0x").toByteStringOrHex())
                 ).build()
             )
-        var gasPrice = quote.tx.gasPrice.toBigIntegerOrNull() ?: BigInteger.ZERO
-        val gas = (quote.tx.gas.takeIf { it != 0L }
-            ?: EvmHelper.Companion.DEFAULT_ETH_SWAP_GAS_UNIT).toBigInteger()
+        var gasPrice = quote.tx.gasPrice.toBigIntegerOrNull()
```
[the remark this answers is not in the document]
Comment (aminsato) [reply data/src/main/kotlin/com/vultisig/wallet/data/api/swapAggregators/KyberSwap.kt:77]: If gas or gasPrice is null, their nullability is handled in setGasParameters
Did I get your idea, or did you mean something else

[the remark this answers is not in the document]
Comment (aminsato) [reply data/src/main/kotlin/com/vultisig/wallet/data/api/swapAggregators/KyberSwap.kt:77]: The issue was that gas value comming from the palyload sometimes equals EvmHelper.DEFAULT_ETH_SWAP_GAS_UNIT which cause the condition if (gas.toLong() != EvmHelper.DEFAULT_ETH_SWAP_GAS_UNIT && gasPrice != BigInteger.ZERO)   to evaluate false
Al cross-platform swaps have been testd, including swap between two Android devices

[the remark this answers is not in the document]
Comment (johnnyluo) [reply data/src/main/kotlin/com/vultisig/wallet/data/api/swapAggregators/KyberSwap.kt:77]: why not change it like this 
`if (gas != BigInteger.ZERO && gasPrice != BigInteger.ZERO)`

**Comment by JaimeToca** [comment]
@aminsato were you able to co-sign iOS/Extension? Anything to change on their end?

**Comment by aminsato** [comment]
> @aminsato were you able to co-sign iOS/Extension? Anything to change on their end?

Yes
Nothing is needed to change on their end

**Review by JaimeToca — APPROVED** [review]
