### PR TITLE
Fix displaying Link token

### LINKED ISSUE #2316: [BUG] Polygon chain shows Link two times in token selection
**Describe the bug**
LINK token gets shown two times on Polygon token selection screen.

**Expected behavior**
ONly show once

**Screenshots**

Image

**Smartphone (please complete the following information):**
 - Version 66

### PR DESCRIPTION
**Pull request by aminsato**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #2316

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **New Features**
  * More comprehensive, incremental token discovery per chain and vault, merging built-in, refreshed and provider tokens with de-duplication.
  * Bridged LINK tokens are clearly labeled in asset lists.

* **Bug Fixes**
  * Fewer duplicate tokens shown; improved fallback when external token lookups fail.

* **Refactor**
  * Token retrieval and token-conversion responsibilities reorganized into dedicated providers; asset selection consumes a unified token stream with no UI changes.

### CODE REVIEW

File: data/src/main/kotlin/com/vultisig/wallet/data/usecases/chaintokens/LinkCoinStrategy.kt [hunk 1]
```diff
@@ -0,0 +1,13 @@
+package com.vultisig.wallet.data.usecases.chaintokens
+
+import com.vultisig.wallet.data.models.Coin
+
+internal object LinkCoinStrategy : CoinModificationStrategy {
+    override fun modify(item: Coin): Coin {
+        require(item.ticker == LINK_TICKER)
```
Comment (JaimeToca) [inline data/src/main/kotlin/com/vultisig/wallet/data/usecases/chaintokens/LinkCoinStrategy.kt:7]: can this condition ever happen? seems a bit redundant

**Review by JaimeToca — APPROVED** [review]

File: data/src/main/kotlin/com/vultisig/wallet/data/usecases/chaintokens/LinkCoinStrategy.kt (hunk 1 above)
Comment (aminsato) [reply data/src/main/kotlin/com/vultisig/wallet/data/usecases/chaintokens/LinkCoinStrategy.kt:7]: @JaimeToca 
The line was added to prevent unintended use of this class - it should only be used for Link token
