### PR TITLE
Fix camera focus square

### LINKED ISSUE #2252: [BUG] - Camera focus square box remains on Home Screen after switching back from device overview
**Environment**:
	•	Device: Redmi Note 10 Pro
	•	OS Version: Android 12
	•	App Version: v1.0.65
	•	Working Fine On: Samsung S23 (Android 15)

**Steps to Reproduce:**
	1.	Open the Vultisig app and go to the Home Screen.
	2.	Tap the Camera icon to open the camera.
	3.	Wait until the focus mode activates (focus square box appears).
	4.	Tap the device overview (square) button to open recent apps.
	5.	Reopen the Vultisig app from the recent apps list.

**Actual Behavior:**
The camera focus square box remains visible on the Home Screen.
https://github.com/user-attachments/assets/6c59b878-047c-419c-800c-46c78436126c

### PR DESCRIPTION
**Pull request by aminsato**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #2252

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **Refactor**
  * Enhanced camera lifecycle management on the QR code scanning screen to ensure smooth preview recreation and reliable camera behavior when returning from background.

### CODE REVIEW

File: app/src/main/java/com/vultisig/wallet/ui/screens/scan/ScanQrScreen.kt [hunk 1]
```diff
@@ -258,81 +262,108 @@ private fun QrCameraScreen(
...
-                BarcodeAnalyzer {
-                    unbindCameraListener(cameraProviderFuture, localContext)
-                    onSuccess(it)
+    DisposableEffect(lifecycleOwner) {
+        val observer = LifecycleEventObserver { _, event ->
+            when (event) {
+                Lifecycle.Event.ON_RESUME -> {
+                    // Force AndroidView to recreate by changing the key
+                    viewKey++
                 }
```
Comment (JaimeToca) [inline app/src/main/java/com/vultisig/wallet/ui/screens/scan/ScanQrScreen.kt:276]: @aminsato this will trigger unnecesary re-composition as will be execute first time. Correct?

Shall we checked that user went through onPause

Comment (aminsato) [reply app/src/main/java/com/vultisig/wallet/ui/screens/scan/ScanQrScreen.kt]: onPause added
