### PR TITLE
Fix race condition when handling custom payload

### LINKED ISSUE #2337: [Android vital log] VerifySignMessageViewModel$1.invokeSuspend
**Describe the bug**
‍‍‍`Exception java.lang.NullPointerException:
    at com.vultisig.wallet.ui.models.sign.VerifySignMessageViewModel$1.invokeSuspend (VerifySignMessageViewModel.kt:48)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
    at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith (DispatchedContinuation.kt:375)
    at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable (Cancellable.kt:26)
    at kotlinx.coroutines.CoroutineStart.invoke (CoroutineStart.java:358)
    at kotlinx.coroutines.AbstractCoroutine.start (AbstractCoroutine.kt:134)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch (BuildersKt__Builders_common.kt:52)
    at kotlinx.coroutines.BuildersKt.launch (Builders.kt:1)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default (BuildersKt__Builders_common.kt:43)
    at kotlinx.coroutines.BuildersKt.launch$default (Builders.kt:1)
    at com.vultisig.wallet.ui.models.sign.VerifySignMessageViewModel.<init> (VerifySignMessageViewModel.kt:47)
    at com.vultisig.wallet.app.DaggerVultisigApplication_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get (DaggerVultisigApplication_HiltComponents_SingletonC.java:1515)
    at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$2.createViewModel (HiltViewModelFactory.java:132)
    at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$2.create (HiltViewModelFactory.java:103)
    at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create (HiltViewModelFactory.java:170)
    at androidx.lifecycle.ViewModelProvider$Factory.create (ViewModelProvider.android.kt:158)
    at androidx.lifecycle.viewmodel.ViewModelProviderImpl_androidKt.createViewModel (ViewModelProviderImpl_android.kt:34)
    at androidx.lifecycle.viewmodel.ViewModelProviderImpl.getViewModel$lifecycle_viewmodel_release (ViewModelProviderImpl.java:65)
    at androidx.lifecycle.viewmodel.ViewModelProviderImpl.getViewModel$lifecycle_viewmodel_release$default (ViewModelProviderImpl.java:47)
    at androidx.lifecycle.ViewModelProvider.get (ViewModelProvider.java:91)
    at androidx.lifecycle.viewmodel.compose.ViewModelKt__ViewModelKt.get (ViewModelKt__ViewModel.kt:162)
    at androidx.lifecycle.viewmodel.compose.ViewModelKt.get (ViewModel.kt:1)
    at androidx.lifecycle.viewmodel.compose.ViewModelKt__ViewModel_androidKt.viewModel (ViewModelKt__ViewModel_android.kt:124)
    at androidx.lifecycle.viewmodel.compose.ViewModelKt.viewModel (ViewModel.kt:1)
    at com.vultisig.wallet.ui.screens.sign.VerifySignMessageScreenKt.VerifySignMessageScreen (VerifySignMessageScreen.kt:205)
    at com.vultisig.wallet.ui.screens.sign.ComposableSingletons$SignMessageScreenKt$lambda$1752676151$1.invoke (SignMessageScreen.kt:115)
    at com.vultisig.wallet.ui.screens.sign.ComposableSingletons$SignMessageScreenKt$lambda$1752676151$1.invoke (SignMessageScreen.kt:114)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:142)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.navigation.compose.NavHostKt$NavHost$32$1.invoke (NavHost.kt:704)
    at androidx.navigation.compose.NavHostKt$NavHost$32$1.invoke (NavHost.kt:703)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:384)
    at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider (SaveableStateHolder.kt:79)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider (NavBackStackEntryProvider.kt:65)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider (NavBackStackEntryProvider.kt:1)
    at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke (NavBackStackEntryProvider.kt:52)
    at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke (NavBackStackEntryProvider.kt:51)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:364)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider (NavBackStackEntryProvider.kt:47)
    at androidx.navigation.compose.NavHostKt$NavHost$32.invoke (NavHost.kt:703)
    at androidx.navigation.compose.NavHostKt$NavHost$32.invoke (NavHost.kt:683)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:142)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke (AnimatedContent.kt:862)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke (AnimatedContent.kt:852)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:130)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl (AnimatedVisibility.kt:755)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke (AnimatedContent.kt:834)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke (AnimatedContent.kt:817)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedContentKt.AnimatedContent (AnimatedContent.kt:872)
    at androidx.navigation.compose.NavHostKt.NavHost (NavHost.kt:655)
    at androidx.navigation.compose.NavHostKt.NavHost (NavHost.kt:212)
    at com.vultisig.wallet.ui.screens.sign.SignMessageScreenKt$SignMessageScreen$6.invoke (SignMessageScreen.kt:96)
    at com.vultisig.wallet.ui.screens.sign.SignMessageScreenKt$SignMessageScreen$6.invoke (SignMessageScreen.kt:95)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:130)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at com.vultisig.wallet.ui.components.ProgressScreenKt$ProgressScreen$2.invoke (ProgressScreen.kt:109)
    at com.vultisig.wallet.ui.components.ProgressScreenKt$ProgressScreen$2.invoke (ProgressScreen.kt:37)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:130)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at com.vultisig.wallet.ui.components.UiBarContainerKt.UiBarContainer (UiBarContainer.kt:39)
    at com.vultisig.wallet.ui.components.ProgressScreenKt.ProgressScreen (ProgressScreen.kt:30)
    at com.vultisig.wallet.ui.screens.sign.SignMessageScreenKt.SignMessageScreen (SignMessageScreen.kt:83)
    at com.vultisig.wallet.ui.navigation.NavGraphKt$SetupNavGraph$1$1$30.invoke (NavGraph.kt:232)
    at com.vultisig.wallet.ui.navigation.NavGraphKt$SetupNavGraph$1$1$30.invoke (NavGraph.kt:229)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:142)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.navigation.compose.NavHostKt$NavHost$32$1.invoke (NavHost.kt:704)
    at androidx.navigation.compose.NavHostKt$NavHost$32$1.invoke (NavHost.kt:703)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:384)
    at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider (SaveableStateHolder.kt:79)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider (NavBackStackEntryProvider.kt:65)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider (NavBackStackEntryProvider.kt:1)
    at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke (NavBackStackEntryProvider.kt:52)
    at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke (NavBackStackEntryProvider.kt:51)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:364)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider (NavBackStackEntryProvider.kt:47)
    at androidx.navigation.compose.NavHostKt$NavHost$32.invoke (NavHost.kt:703)
    at androidx.navigation.compose.NavHostKt$NavHost$32.invoke (NavHost.kt:683)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:142)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke (AnimatedContent.kt:862)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke (AnimatedContent.kt:852)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:130)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl (AnimatedVisibility.kt:755)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke (AnimatedContent.kt:834)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke (AnimatedContent.kt:817)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedContentKt.AnimatedContent (AnimatedContent.kt:872)
    at androidx.navigation.compose.NavHostKt.NavHost (NavHost.kt:655)
    at androidx.navigation.compose.NavHostKt$NavHost$34.invoke (NavHost.kt:113)
    at androidx.navigation.compose.NavHostKt$NavHost$34.invoke (NavHost.kt:113)
    at androidx.compose.runtime.RecomposeScopeImpl.compose (RecomposeScopeImpl.java:235)
    at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd (Composer.kt:2838)
    at androidx.compose.runtime.ComposerImpl.skipCurrentGroup (Composer.kt:3158)
    at androidx.compose.runtime.ComposerImpl.doCompose-aFTiNEg (Composer.kt:3706)
    at androidx.compose.runtime.ComposerImpl.recompose-aFTiNEg$runtime_release (Composer.kt:3648)
    at androidx.compose.runtime.CompositionImpl.recompose (Composition.kt:1002)
    at androidx.compose.runtime.Recomposer.performRecompose (Recomposer.kt:1266)
    at androidx.compose.runtime.Recomposer.access$performRecompose (Recomposer.kt:142)
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke (Recomposer.kt:620)
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke (Recomposer.kt:591)
    at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame (AndroidUiFrameClock.android.kt:39)
    at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch (AndroidUiDispatcher.java:108)
    at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch (AndroidUiDispatcher.java:41)
    at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame (AndroidUiDispatcher.android.kt:69)
    at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1127)
    at android.view.Choreographer.doCallbacks (Choreographer.java:918)
    at android.view.Choreographer.doFrame (Choreographer.java:824)
    at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1112)
    at android.os.Handler.handleCallback (Handler.java:938)
    at android.os.Handler.dispatchMessage (Handler.java:99)
    at android.os.Looper.loopOnce (Looper.java:241)
    at android.os.Looper.loop (Looper.java:342)
    at android.app.ActivityThread.main (ActivityThread.java:8143)
    at java.lang.reflect.Method.invoke
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:583)
    at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1045)
Exception java.lang.NullPointerException:
    at com.vultisig.wallet.ui.models.sign.VerifySignMessageViewModel$1.invokeSuspend (VerifySignMessageViewModel.kt:48)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
    at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith (DispatchedContinuation.kt:375)
    at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable (Cancellable.kt:26)
    at kotlinx.coroutines.CoroutineStart.invoke (CoroutineStart.java:358)
    at kotlinx.coroutines.AbstractCoroutine.start (AbstractCoroutine.kt:134)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch (BuildersKt__Builders_common.kt:52)
    at kotlinx.coroutines.BuildersKt.launch (Builders.kt:1)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default (BuildersKt__Builders_common.kt:43)
    at kotlinx.coroutines.BuildersKt.launch$default (Builders.kt:1)
    at com.vultisig.wallet.ui.models.sign.VerifySignMessageViewModel.<init> (VerifySignMessageViewModel.kt:47)
    at com.vultisig.wallet.app.DaggerVultisigApplication_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get (DaggerVultisigApplication_HiltComponents_SingletonC.java:1515)
    at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$2.createViewModel (HiltViewModelFactory.java:132)
    at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$2.create (HiltViewModelFactory.java:103)
    at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create (HiltViewModelFactory.java:170)
    at androidx.lifecycle.ViewModelProvider$Factory.create (ViewModelProvider.android.kt:158)
    at androidx.lifecycle.viewmodel.ViewModelProviderImpl_androidKt.createViewModel (ViewModelProviderImpl_android.kt:34)
    at androidx.lifecycle.viewmodel.ViewModelProviderImpl.getViewModel$lifecycle_viewmodel_release (ViewModelProviderImpl.java:65)
    at androidx.lifecycle.viewmodel.ViewModelProviderImpl.getViewModel$lifecycle_viewmodel_release$default (ViewModelProviderImpl.java:47)
    at androidx.lifecycle.ViewModelProvider.get (ViewModelProvider.java:91)
    at androidx.lifecycle.viewmodel.compose.ViewModelKt__ViewModelKt.get (ViewModelKt__ViewModel.kt:162)
    at androidx.lifecycle.viewmodel.compose.ViewModelKt.get (ViewModel.kt:1)
    at androidx.lifecycle.viewmodel.compose.ViewModelKt__ViewModel_androidKt.viewModel (ViewModelKt__ViewModel_android.kt:124)
    at androidx.lifecycle.viewmodel.compose.ViewModelKt.viewModel (ViewModel.kt:1)
    at com.vultisig.wallet.ui.screens.sign.VerifySignMessageScreenKt.VerifySignMessageScreen (VerifySignMessageScreen.kt:205)
    at com.vultisig.wallet.ui.screens.sign.ComposableSingletons$SignMessageScreenKt$lambda$1752676151$1.invoke (SignMessageScreen.kt:115)
    at com.vultisig.wallet.ui.screens.sign.ComposableSingletons$SignMessageScreenKt$lambda$1752676151$1.invoke (SignMessageScreen.kt:114)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:142)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.navigation.compose.NavHostKt$NavHost$32$1.invoke (NavHost.kt:704)
    at androidx.navigation.compose.NavHostKt$NavHost$32$1.invoke (NavHost.kt:703)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:384)
    at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider (SaveableStateHolder.kt:79)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider (NavBackStackEntryProvider.kt:65)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider (NavBackStackEntryProvider.kt:1)
    at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke (NavBackStackEntryProvider.kt:52)
    at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke (NavBackStackEntryProvider.kt:51)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:364)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider (NavBackStackEntryProvider.kt:47)
    at androidx.navigation.compose.NavHostKt$NavHost$32.invoke (NavHost.kt:703)
    at androidx.navigation.compose.NavHostKt$NavHost$32.invoke (NavHost.kt:683)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:142)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke (AnimatedContent.kt:862)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke (AnimatedContent.kt:852)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:130)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl (AnimatedVisibility.kt:755)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke (AnimatedContent.kt:834)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke (AnimatedContent.kt:817)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedContentKt.AnimatedContent (AnimatedContent.kt:872)
    at androidx.navigation.compose.NavHostKt.NavHost (NavHost.kt:655)
    at androidx.navigation.compose.NavHostKt.NavHost (NavHost.kt:212)
    at com.vultisig.wallet.ui.screens.sign.SignMessageScreenKt$SignMessageScreen$6.invoke (SignMessageScreen.kt:96)
    at com.vultisig.wallet.ui.screens.sign.SignMessageScreenKt$SignMessageScreen$6.invoke (SignMessageScreen.kt:95)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:130)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at com.vultisig.wallet.ui.components.ProgressScreenKt$ProgressScreen$2.invoke (ProgressScreen.kt:109)
    at com.vultisig.wallet.ui.components.ProgressScreenKt$ProgressScreen$2.invoke (ProgressScreen.kt:37)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:130)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at com.vultisig.wallet.ui.components.UiBarContainerKt.UiBarContainer (UiBarContainer.kt:39)
    at com.vultisig.wallet.ui.components.ProgressScreenKt.ProgressScreen (ProgressScreen.kt:30)
    at com.vultisig.wallet.ui.screens.sign.SignMessageScreenKt.SignMessageScreen (SignMessageScreen.kt:83)
    at com.vultisig.wallet.ui.navigation.NavGraphKt$SetupNavGraph$1$1$30.invoke (NavGraph.kt:232)
    at com.vultisig.wallet.ui.navigation.NavGraphKt$SetupNavGraph$1$1$30.invoke (NavGraph.kt:229)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:142)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.navigation.compose.NavHostKt$NavHost$32$1.invoke (NavHost.kt:704)
    at androidx.navigation.compose.NavHostKt$NavHost$32$1.invoke (NavHost.kt:703)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:384)
    at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider (SaveableStateHolder.kt:79)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider (NavBackStackEntryProvider.kt:65)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider (NavBackStackEntryProvider.kt:1)
    at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke (NavBackStackEntryProvider.kt:52)
    at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke (NavBackStackEntryProvider.kt:51)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:364)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider (NavBackStackEntryProvider.kt:47)
    at androidx.navigation.compose.NavHostKt$NavHost$32.invoke (NavHost.kt:703)
    at androidx.navigation.compose.NavHostKt$NavHost$32.invoke (NavHost.kt:683)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:142)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke (AnimatedContent.kt:862)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke (AnimatedContent.kt:852)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:130)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl (AnimatedVisibility.kt:755)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke (AnimatedContent.kt:834)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke (AnimatedContent.kt:817)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedContentKt.AnimatedContent (AnimatedContent.kt:872)
    at androidx.navigation.compose.NavHostKt.NavHost (NavHost.kt:655)
    at androidx.navigation.compose.NavHostKt$NavHost$34.invoke (NavHost.kt:113)
    at androidx.navigation.compose.NavHostKt$NavHost$34.invoke (NavHost.kt:113)
    at androidx.compose.runtime.RecomposeScopeImpl.compose (RecomposeScopeImpl.java:235)
    at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd (Composer.kt:2838)
    at androidx.compose.runtime.ComposerImpl.skipCurrentGroup (Composer.kt:3158)
    at androidx.compose.runtime.ComposerImpl.doCompose-aFTiNEg (Composer.kt:3706)
    at androidx.compose.runtime.ComposerImpl.recompose-aFTiNEg$runtime_release (Composer.kt:3648)
    at androidx.compose.runtime.CompositionImpl.recompose (Composition.kt:1002)
    at androidx.compose.runtime.Recomposer.performRecompose (Recomposer.kt:1266)
    at androidx.compose.runtime.Recomposer.access$performRecompose (Recomposer.kt:142)
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke (Recomposer.kt:620)
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke (Recomposer.kt:591)
    at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame (AndroidUiFrameClock.android.kt:39)
    at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch (AndroidUiDispatcher.java:108)
    at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch (AndroidUiDispatcher.java:41)
    at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame (AndroidUiDispatcher.android.kt:69)
    at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1127)
    at android.view.Choreographer.doCallbacks (Choreographer.java:918)
    at android.view.Choreographer.doFrame (Choreographer.java:824)
    at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1112)
    at android.os.Handler.handleCallback (Handler.java:938)
    at android.os.Handler.dispatchMessage (Handler.java:99)
    at android.os.Looper.loopOnce (Looper.java:241)
    at android.os.Looper.loop (Looper.java:342)
    at android.app.ActivityThread.main (ActivityThread.java:8143)
    at java.lang.reflect.Method.invoke
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:583)
    at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1045)
`
**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel]

**Additional context**

### PR DESCRIPTION
**Pull request by aminsato**
## Description
The error  was caused by a race condition between writing a value to a map inside viewmodelScope and reading  it from another viewmodelScope.
To fix this, I convertd  the getter into a suspend function so it waits untill the  setter completes before  accessing the value.This ensures the value is always initialized before read, preventing race condition and eliminating NullPointerExceptions

Fixes #2337

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **Bug Fixes**
  * Prevented potential crashes during message verification caused by missing or delayed payloads.
  * Improved reliability of loading sign message payloads, reducing intermittent failures.
  * Enhanced responsiveness in the message verification flow, providing a smoother user experience.
  * Ensured consistent behavior when retrieving custom message payloads during signing and verification.

### CODE REVIEW

File: data/src/main/kotlin/com/vultisig/wallet/data/repositories/CustomMessagePayloadRepo.kt [hunk 1]
```diff
@@ -12,18 +16,18 @@ data class CustomMessagePayloadDto(
...
 
     override fun add(payload: CustomMessagePayloadDto) {
-        payloads[payload.id] = payload
+        _payloads.update { it + (payload.id to payload) }
     }
 
-    override fun get(id: String): CustomMessagePayloadDto? {
-        return payloads[id]
+    override suspend fun get(id: String): CustomMessagePayloadDto {
+        return _payloads.mapNotNull { it[id] }.first()
```
Comment (JaimeToca) [inline data/src/main/kotlin/com/vultisig/wallet/data/repositories/CustomMessagePayloadRepo.kt:30]: What is the actual effect of making this suspend outside this repo?

Comment (aminsato) [reply data/src/main/kotlin/com/vultisig/wallet/data/repositories/CustomMessagePayloadRepo.kt:30]: The suspension ensures the getter waits for a new value.
Currently, the map’s setter and getter run in separate scopes, which can cause race conditions — sometimes the getter is called before the setter completes, resulting in a NullPointerException.
To resolve this, I converted the map into a Flow. Now, if the getter is invoked before the setter updates the value, it will suspend until the value becomes available

Comment (JaimeToca) [reply data/src/main/kotlin/com/vultisig/wallet/data/repositories/CustomMessagePayloadRepo.kt:30]: if this does not trigger any other side behaviour is fine. If not, I advice handle null properly, for example as: _payloads.mapNotNull { it[id] }.firstOrNull() , and removing suspend

**Review by JaimeToca — APPROVED** [review]
