### PR TITLE
Fix DeFi chain selector

### LINKED ISSUE #2738: [ADD] DeFi Chain Selector
Create DeFi Chain Selector According
https://github.com/vultisig/vultisig-android/issues/2612

### PR DESCRIPTION
**Pull request by aminsato**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #2738

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **New Features**
  * New UI model for token items enabling single or paired token displays with split-logo visuals and paired-name formatting.
  * Grouped token lists with an optional configurable “+” action per group.

* **Bug Fixes**
  * More consistent token logo loading and display across single and paired items.

* **Refactor**
  * Token selection and grid rendering rewired for group-driven rendering and unified item handling.

### CODE REVIEW

**Comment by JaimeToca** [comment]
Hi Amin, could you :
- Add preview of the dialog
- Show it when clicking on the actual button

File: app/src/main/java/com/vultisig/wallet/ui/components/v2/tokenitem/ChainSelectionItem.kt [hunk 1]
```diff
@@ -165,23 +167,186 @@ internal fun GridPlus(
...
+            .widthIn(max = 74.dp),
+        maxLines = 1,
+        overflow = TextOverflow.Ellipsis
+    )
+}
+
+@Composable
+private fun TokenUiGridName(
+    tokens: TokenSelectionUiModel.TokenUiPair,
+    mapper: (TokenSelectionUiModel.TokenUiPair) -> String = { "${it.left.name}/${it.right.name}" },
```
Comment (JaimeToca) [inline app/src/main/java/com/vultisig/wallet/ui/components/v2/tokenitem/ChainSelectionItem.kt]: how this is meant to be used? It would be nice if you can have preview of full dialog 👍🏻

**Comment by aminsato** [comment]
@JaimeToca 
I also add support for rendering two images inside a single token grid item 
image
