### PR TITLE
Fix FileHelper crash

### LINKED ISSUE #2469: [Android Vitals crash] FileHelperKt.saveBitmapToDownloadsDirAtLeastQ
```
Exception java.lang.IllegalStateException:
    at android.os.Parcel.createExceptionOrNull (Parcel.java:3265)
    at android.os.Parcel.createException (Parcel.java:3241)
    at android.os.Parcel.readException (Parcel.java:3224)
    at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:203)
    at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:155)
    at android.content.ContentProviderProxy.insert (ContentProviderNative.java:589)
    at android.content.ContentResolver.insert (ContentResolver.java:2222)
    at android.content.ContentResolver.insert (ContentResolver.java:2184)
    at com.vultisig.wallet.data.common.FileHelperKt.saveBitmapToDownloadsDirAtLeastQ (FileHelper.kt:118)
    at com.vultisig.wallet.data.common.FileHelperKt.saveBitmapToDownloads (FileHelper.kt:98)
    at com.vultisig.wallet.ui.models.ShareVaultQrViewModel$saveBitmap$1.invokeSuspend (ShareVaultQrViewModel.kt:175)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:100)
    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run (LimitedDispatcher.java:113)
    at kotlinx.coroutines.scheduling.TaskImpl.run (Tasks.kt:89)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.java:586)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:820)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:717)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:704)

```

### PR DESCRIPTION
**Pull request by aminsato**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #2469

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

- New Features
  - QR screen now uses a persistent bottom bar with Share and Save actions for easier access.
  - Added localized error messages for QR save failures (EN, DE, ES, HR, IT, NL, PT, RU).

- Bug Fixes
  - Improved error handling when saving QR codes, showing clear snackbar feedback on failure.
  - Refined post-save behavior: success message shown when saved, with appropriate navigation.

### CODE REVIEW

File: app/src/main/java/com/vultisig/wallet/ui/screens/ShareVaultQrScreen.kt [hunk 1]
```diff
@@ -140,7 +140,38 @@ internal fun ShareVaultQrScreen(
...
+
+                VsButton(
+                    label = stringResource(R.string.share_vault_qr_save),
+                    onClick = onSaveClick,
+                    modifier = Modifier.fillMaxWidth(),
+                    size = VsButtonSize.Medium,
+                    variant = VsButtonVariant.Secondary
+                )
+            }
+        }
```
Comment (aminsato) [inline app/src/main/java/com/vultisig/wallet/ui/screens/ShareVaultQrScreen.kt:174]: Use bottom bar the bottom buttons to ensure they display properly on smaller screens
