### PR TITLE
Fix duplicate ETH token

### LINKED ISSUE #1978: [BUG] WstETH on Ethereum is displayed twice
**Describe the bug**
When holding WstETH in the wallet, it gets displayed twice one as `WstETH` and `WSTETH`. While the latter one should not be fetched or displayed

**To Reproduce**
1. Have WstETH in the wallet
2. refresh

**Expected behavior**
Just show the correct WstETH in the wallet

**Screenshots**

Image

**Smartphone (please complete the following information):**
 - Version 56

### PR DESCRIPTION
**Pull request by aminsato**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #1978

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved token filtering to be case-insensitive when identifying disabled tokens, ensuring more accurate token selection.
  * Updated token deduplication logic to use contract address and chain ID for uniqueness, preventing duplicate tokens with the same contract address on the same chain.

### CODE REVIEW

File: app/src/main/java/com/vultisig/wallet/data/db/migrations/MIGRATIONS.kt [hunk 1]
```diff
@@ -428,4 +428,34 @@ internal val MIGRATION_22_23 = object : Migration(22, 23) {
         """.trimIndent()
         )
     }
+}
+
+internal val MIGRATION_23_24 = object : Migration(23, 24) {
+
+    override fun migrate(database: SupportSQLiteDatabase) {
```
Comment (johnnyluo) [inline app/src/main/java/com/vultisig/wallet/data/db/migrations/MIGRATIONS.kt:435]: Let's not do this, if user have duplicate tokens , they can remove the token and add it back to remove the duplication

Comment (aminsato) [reply app/src/main/java/com/vultisig/wallet/data/db/migrations/MIGRATIONS.kt]: Done

**Review by johnnyluo — APPROVED** [review]
LGTM
