### PR TITLE
Fix UnknownHostException 

### LINKED ISSUE #3187: [Google play crash log] UnknownHostException
- Versions affected: 93
- Motorola moto g stylus 5G - 2025
- Android 15.0 (API 35)
-  Feb 2, 2026, 11:30:00 AM

- Commit details
  - https://github.com/vultisig/vultisig-android/commit/7c2ce5845ef1462cc09a0af206f30862f63fde45

Logs
```
Exception java.net.UnknownHostException:
    at java.net.Inet6AddressImpl.lookupHostByName (Inet6AddressImpl.java:156)
    at java.net.Inet6AddressImpl.lookupAllHostAddr (Inet6AddressImpl.java:103)
    at java.net.InetAddress.getAllByName (InetAddress.java:1152)
    at okhttp3.Dns$Companion$DnsSystem.lookup (Dns.kt:49)
    at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress (RouteSelector.kt:169)
    at okhttp3.internal.connection.RouteSelector.nextProxy (RouteSelector.kt:131)
    at okhttp3.internal.connection.RouteSelector.next (RouteSelector.kt:73)
    at okhttp3.internal.connection.ExchangeFinder.findConnection (ExchangeFinder.kt:205)
    at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection (ExchangeFinder.kt)
    at okhttp3.internal.connection.ExchangeFinder.find (ExchangeFinder.kt:74)
    at okhttp3.internal.connection.RealCall.initExchange$okhttp (RealCall.kt:255)
    at okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.kt:32)
    at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
    at okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.kt:95)
    at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
    at okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.kt:83)
    at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.kt:76)
    at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp (RealCall.kt:201)
    at okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:517)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1154)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:652)
    at java.lang.Thread.run (Thread.java:1563)
Caused by android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
    at libcore.io.Linux.android_getaddrinfo
    at libcore.io.ForwardingOs.android_getaddrinfo (ForwardingOs.java:134)
    at libcore.io.BlockGuardOs.android_getaddrinfo (BlockGuardOs.java:222)
    at libcore.io.ForwardingOs.android_getaddrinfo (ForwardingOs.java:134)
    at java.net.Inet6AddressImpl.lookupHostByName (Inet6AddressImpl.java:135)

```

### PR DESCRIPTION
**Pull request by aminsato**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #3187

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved network error handling to gracefully synthesize error responses instead of propagating exceptions, preventing potential crashes.

* **Tests**
  * Added comprehensive test infrastructure and test cases to validate network error scenarios, including connection failures, timeouts, and DNS resolution issues.

### CODE REVIEW

File: app/src/main/java/com/vultisig/wallet/data/di/NetworkModule.kt [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+            }
+            install(ContentNegotiation) {
+                json(json, ContentType.Any)
+            }
+
+            install(HttpRequestRetry) {
+                retryOnServerErrors(maxRetries = 3)
+                exponentialDelay()
+
+                retryIf { request, response ->
```
Comment (rkokhatskyi) [inline app/src/main/java/com/vultisig/wallet/data/di/NetworkModule.kt]: few things missing from the old DataModule: 

- `retryOnException` was removed, is that intentional? 
- Ktor HttpTimeout plugin - now we don't configure timeout and retried requests can be hanging for some time (longer than should)

File: app/src/androidTest/java/com/vultisig/wallet/network/FaultyInterceptor.kt [hunk 2]
```diff
@@ -0,0 +1,28 @@
+package com.vultisig.wallet.network
+
+import okhttp3.Interceptor.Chain
+import okhttp3.Protocol
+import okhttp3.Response
+import okhttp3.ResponseBody.Companion.toResponseBody
+
+class FaultyInterceptor {
```
Comment (rkokhatskyi) [inline app/src/androidTest/java/com/vultisig/wallet/network/FaultyInterceptor.kt]: Please make it implement Interceptor class

File: app/src/main/java/com/vultisig/wallet/data/di/NetworkModule.kt (hunk 1 above)
Comment (aminsato) [reply app/src/main/java/com/vultisig/wallet/data/di/NetworkModule.kt]: Ktor’s HttpTimeout plugin wraps the request outside the OkHttp engine. If Ktor’s timer runs out, it throws HttpRequestTimeoutException before  NetworkStateInterceptor has a chance to catch the underlying SocketTimeoutException and convert it to a 503. Moving timeouts to the Engine level ensures the exception happens inside OkHttp, allowing Interceptor to catch it.

**Comment by aminsato** [comment]
> @aminsato we should not add custom code to handle these types of error , DNS should be handled by the OS
> 
> Can you please make sure it doesn't crash instead?

Done

File: data/src/main/kotlin/com/vultisig/wallet/data/networkutils/HttpClientConfigurator.kt [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+                    retryOnTimeout = true
+                )
+
+                retryIf { request, response ->
+                    val method = request.method
+                    val status = response.status.value
+
+                    val isSafeMethod = method == HttpMethod.Get ||
+                            method == HttpMethod.Head ||
+                            method == HttpMethod.Options
```
Comment (rkokhatskyi) [inline data/src/main/kotlin/com/vultisig/wallet/data/networkutils/HttpClientConfigurator.kt]: Why GET, HEAD and OPTIONS are considered safe now, but not other methods like POST / PUT etc.

Comment (aminsato) [reply data/src/main/kotlin/com/vultisig/wallet/data/networkutils/HttpClientConfigurator.kt]: Because these methods only read server data and are not used to send changes to the server

File: data/src/main/kotlin/com/vultisig/wallet/data/networkutils/HttpClientConfigurator.kt [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+            }
+
+            install(HttpRequestRetry) {
+                exponentialDelay()
+                retryOnException(
+                    maxRetries = 3,
+                    retryOnTimeout = true
+                )
+
+                retryIf { request, response ->
```
[the remark this answers is not in the document]
Comment (aminsato) [reply data/src/main/kotlin/com/vultisig/wallet/data/networkutils/HttpClientConfigurator.kt]: In `retryOnException`, it is executed when the exception is from the user side, but retryIf is executed when the exception is in the server response.

File: data/src/main/kotlin/com/vultisig/wallet/data/networkutils/HttpClientConfigurator.kt (hunk 3 above)
Comment (rkokhatskyi) [reply data/src/main/kotlin/com/vultisig/wallet/data/networkutils/HttpClientConfigurator.kt]: We do use POST and DELETE as well, are we going to ignore them?

File: data/src/main/kotlin/com/vultisig/wallet/data/networkutils/NetworkInterceptor.kt [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+            // This prevents the exception from bubbling up and crashing the app.
+            // We use HTTP 503 (Service Unavailable) as a generic container.
+            val mediaType = "application/json".toMediaTypeOrNull()
+            val errorMessage = "{\"error\": \"Network failure: ${e.localizedMessage}\"}"
+            val responseBody = errorMessage.toResponseBody(mediaType)
+
+            return Response.Builder()
+                .request(request)
+                .protocol(Protocol.HTTP_1_1)
+                .code(HttpStatusCode.ServiceUnavailable.value)
```
[the remark this answers is not in the document]
Comment (rkokhatskyi) [reply data/src/main/kotlin/com/vultisig/wallet/data/networkutils/NetworkInterceptor.kt]: @aminsato I added a test that proves current falty behaviour, please merge the PR with tests into your branch https://github.com/vultisig/vultisig-android/pull/3232 - you can check the expected results from tests and adjust your code logic
