### PR TITLE
Fix selection of assets in Cosmos function that are not enabled

### LINKED ISSUE #2227: [BUG] Cosmos Function
**Describe the bug**
Doing a Deposit on Cosmos chain have an issue
To Reproduce
1. Steps to reproduce the behavior:
2. Perform a Cosmos chain function
3. Select IBC Transfer
4. Select Destination Chain as Kujira (ukuji)
5. Select Asset as KUJI
6. See error

**Expected behavior**

**Screenshots**

https://github.com/user-attachments/assets/2a679361-19e8-4460-99ac-60f4484278e3

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel]

**Additional context**

### PR DESCRIPTION
**Pull request by aminsato**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #2227

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **New Features**
  * Deposit flow now auto-enables missing tokens and refreshes addresses so balances update automatically.

* **Bug Fixes**
  * More reliable balance display and cleared amount errors when tokens or accounts are absent.

* **Validation**
  * IBC deposits now require non-empty, chain-valid destination addresses with explicit error messages.

* **Localization**
  * Added localized error strings for empty/invalid destination addresses in multiple languages.

### CODE REVIEW

File: app/src/main/java/com/vultisig/wallet/ui/models/deposit/DepositFormViewModel.kt [hunk 1]
```diff
@@ -264,29 +264,51 @@ internal class DepositFormViewModel @Inject constructor(
...
+                }
+
+                val tokenValue = account?.tokenValue
+                if (tokenValue == null) {
+                    state.update {
+                        it.copy(
+                            balance = UiText.Empty,
+                            amountError ="$tickerToActivate must be enabled before proceeding.".asUiText()
+                        )
+                    }
```
Comment (JaimeToca) [inline app/src/main/java/com/vultisig/wallet/ui/models/deposit/DepositFormViewModel.kt:301]: I think it is better experience for the user if we enable the asset actually us, same as swap. We show assets not enabled, if user selects, we enable (and fetch balance if required)

Comment (aminsato) [reply app/src/main/java/com/vultisig/wallet/ui/models/deposit/DepositFormViewModel.kt:301]: Do we enable Kuji for users on the IBC transfer screen if they haven't already when Kuji is the default asset? 🤔 And in the swap form, do we enable the selected token and keep it even when deselected?

**Review by johnnyluo — APPROVED** [review]
LGTM
