### PR TITLE
Wrap navigation in try-catch to log navigation errors

### LINKED ISSUE #2244: [Google console log] NavController.navigate crash
**Describe the bug**
`Exception java.lang.IllegalArgumentException:
    at androidx.navigation.NavController.navigate (NavController.java:2447)
    at androidx.navigation.NavController.navigate$default (NavController.java:2418)
    at androidx.navigation.NavController.navigate (NavController.java:2401)
    at com.vultisig.wallet.ui.navigation.NavControllerKt.route (NavController.kt:14)
    at com.vultisig.wallet.app.activity.MainActivity$onCreate$3$1$1$1$1.emit (MainActivity.java:85)
    at com.vultisig.wallet.app.activity.MainActivity$onCreate$3$1$1$1$1.emit (MainActivity.java:84)
    at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl (SharedFlow.kt:397)
    at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend (SharedFlow.kt:12)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:100)
    at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch (AndroidUiDispatcher.android.kt:79)
    at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch (AndroidUiDispatcher.android.kt:41)
    at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run (AndroidUiDispatcher.android.kt:57)
    at android.os.Handler.handleCallback (Handler.java:958)
    at android.os.Handler.dispatchMessage (Handler.java:99)
    at android.os.Looper.loopOnce (Looper.java:230)
    at android.os.Looper.loop (Looper.java:319)
    at android.app.ActivityThread.main (ActivityThread.java:8893)
    at java.lang.reflect.Method.invoke
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:608)
    at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1103)
`
**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel]

**Additional context**

### PR DESCRIPTION
**Pull request by aminsato**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #2244

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved navigation error handling to provide clearer error messages if navigation fails.

### CODE REVIEW

File: app/src/main/java/com/vultisig/wallet/ui/navigation/NavController.kt [hunk 1]
```diff
@@ -11,8 +11,19 @@ internal fun NavController.route(route: String, opts: NavigationOptions? = null)
...
+                    this,
+                    opts
+                )
+            }
+        } catch (e: IllegalArgumentException) {
+            Timber.e(
+                e,
+                "Navigation failed for route: $route"
+            )
+            error("Navigation failed for route: $route")
```
Comment (johnnyluo) [inline app/src/main/java/com/vultisig/wallet/ui/navigation/NavController.kt:26]: will this throw the error again?

Comment (aminsato) [reply app/src/main/java/com/vultisig/wallet/ui/navigation/NavController.kt:26]: Yup, but this time I want to catch the exact route causing the exception.
I could set a default route to fall back on when an exception occurs, but I believe it's better to surface the actual details of the problem rather than masking it with fallback logic.

Comment (aminsato) [reply app/src/main/java/com/vultisig/wallet/ui/navigation/NavController.kt:26]: There might be an unknown error occurring on some devices that has been reported.

**Comment by JaimeToca** [comment]
Hi @aminsato LGTM, although not sure how you plan to get more info for the error with this. Did an user already report it and we're printing the error on the screen? or just adding it for debugging purposes?

**Review by JaimeToca — APPROVED** [review]
