### PR TITLE
Fix backup password handling more information

### LINKED ISSUE #2270: [BUG Release v1.0.66]- Backup Password screen - info is not functioning.
1. In Backup screen - use password option - land on to Password screen 
2. Tap on info icon 

**Actual**: Not clickable
https://github.com/user-attachments/assets/55dbd669-a882-4d5e-859d-2f63c216ba2b

### PR DESCRIPTION
**Pull request by aminsato**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #2270

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

- New Features
  - Added a “More info” section to the backup password screen, with clear show/hide controls for additional guidance.
  - The screen now retains and reflects the visibility state of the “More info” panel, ensuring a consistent experience when interacting with help content.
  - Improved on-screen actions to toggle help content directly from the backup password UI.

### CODE REVIEW

File: app/src/main/java/com/vultisig/wallet/ui/models/BackupPasswordViewModel.kt [hunk 1]
```diff
@@ -72,6 +73,12 @@ internal class BackupPasswordViewModel @Inject constructor(
 
     val createDocumentRequestFlow = MutableSharedFlow<String>()
 
+    private var isMoreInfoVisible: Boolean
+        get() = state.value.isMoreInfoVisible
+        set(value) = state.update {
+            it.copy(isMoreInfoVisible = value)
+        }
+
```
Comment (JaimeToca) [inline app/src/main/java/com/vultisig/wallet/ui/models/BackupPasswordViewModel.kt:81]: not used on the UI Screen. is the only purpose trigger recomposition?

Comment (aminsato) [reply app/src/main/java/com/vultisig/wallet/ui/models/BackupPasswordViewModel.kt:81]: @JaimeToca
When a new value is assigned to the isMoreInfoVisible variable, its set method is invoked. This triggers the state.update method, causing the composable to recompose with the new boolean value.

Both are using the same component, FastVaultPasswordScreen, and the animations are handled inside that component

**Review by JaimeToca — APPROVED** [review]
