### PR TITLE
Fix onboarding not showing 4th page

### LINKED ISSUE #697: BUG: Missing Onboarding screen on setup
**Describe the bug**
When setting up the app first time the last onboarding screen is missing. See video

**Expected behavior**
Have the last slide displayed

**Screenshots**
https://github.com/user-attachments/assets/cd0e3821-8815-4056-a1e8-340e28916c66

-v14

### PR DESCRIPTION
**Pull request by yvebe**
Closes #697

### CODE REVIEW

File: app/src/main/java/com/vultisig/wallet/presenter/welcome/WelcomeScreen.kt [hunk 1]
```diff
@@ -59,7 +59,7 @@ internal fun WelcomeScreen(
                 }
 
                 is ScrollToNextPage -> {
-                    if (pagerState.currentPage < 2)
+                    if (pagerState.currentPage < 3)
```
Comment (yevhen1sec) [inline app/src/main/java/com/vultisig/wallet/presenter/welcome/WelcomeScreen.kt:62]:
```suggestion
                    if (pagerState.currentPage < pagerState.pageCount - 1)
```

Comment (yevhen1sec) [reply app/src/main/java/com/vultisig/wallet/presenter/welcome/WelcomeScreen.kt:62]: better not use hardcode

**Review by yevhen1sec — CHANGES_REQUESTED** [review]

**Review by yevhen1sec — APPROVED** [review]
