### PR TITLE
Fix rearranging rolders 

### LINKED ISSUE #2163: [BUG] - App Crash on Rearranging Folders in Vaults List Screen
Platform: Android
App Version: v1.0.23
Severity: 🛑 Critical (App Crash)
Status: 🐛 New

⸻

🔁 Steps to Reproduce:
	1.	Launch the app and navigate to the Vaults List screen.
	2.	Tap on “+” or equivalent to create multiple folders (e.g., Folder A, Folder B, Folder C).
	3.	Tap “Edit” to enter rearrangement mode.
	4.	Drag and drop folders to rearrange their order.
	5.	Observe the behavior.

⸻

❌ Actual Result:

App crashes immediately upon rearranging folders.

📱 Environment:
	•	Device: Redmi Android devices 
	•	OS Version: Android 12
	•	App Version: v1.0.23
https://github.com/user-attachments/assets/30a4bb72-e2ac-4643-9fa0-13a89fcbfde4

### PR DESCRIPTION
**Pull request by aminsato**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #2163

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved stability when moving folders by preventing potential errors if a folder is missing during the operation.

### CODE REVIEW

File: app/src/main/java/com/vultisig/wallet/ui/models/home/VaultListViewModel.kt [hunk 1]
```diff
@@ -79,8 +79,8 @@ internal class VaultListViewModel @Inject constructor(
         reIndexJob = viewModelScope.launch {
             delay(500)
             val midOrder = updatedPositionsList[newOrder].id.toString()
-            val upperOrder = updatedPositionsList.getOrNull(newOrder + 1)?.id.toString()
-            val lowerOrder = updatedPositionsList.getOrNull(newOrder - 1)?.id.toString()
+            val upperOrder = updatedPositionsList.getOrNull(newOrder + 1)?.id?.toString()
+            val lowerOrder = updatedPositionsList.getOrNull(newOrder - 1)?.id?.toString()
```
Comment (JaimeToca) [inline app/src/main/java/com/vultisig/wallet/ui/models/home/VaultListViewModel.kt:83]: what would happen when is null?

Comment (aminsato) [reply app/src/main/java/com/vultisig/wallet/ui/models/home/VaultListViewModel.kt:83]: https://github.com/vultisig/vultisig-android/blob/84335ec50408cea3d6a8ff261b963d6f7d8e3228/data/src/main/kotlin/com/vultisig/wallet/data/repositories/order/OrderRepository.kt#L34

**Review by JaimeToca — APPROVED** [review]
