### PR TITLE
Fix loadTransaction crash

### LINKED ISSUE #3217: [Google play crash log] KeysignShareViewModel.loadTransaction
- Versions affected: 95
- Samsung Galaxy S23+
- Android 14.0 (API 34) 
- Feb 12, 2026, 02:30:00 AM

**Stack trace**
```
"main" tid=1 Timed Waiting
    at jdk.internal.misc.Unsafe.park (Native method)
    at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:269)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking (BlockingCoroutine.java:98)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking (BuildersKt__Builders.kt:69)
    at kotlinx.coroutines.BuildersKt.runBlocking (Builders.kt:1)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default (BuildersKt__Builders.kt:47)
    at kotlinx.coroutines.BuildersKt.runBlocking$default (Builders.kt:1)
    at com.vultisig.wallet.ui.models.keysign.KeysignShareViewModel.loadTransaction (KeysignShareViewModel.java:71)
    at com.vultisig.wallet.ui.screens.keysign.KeysignScreenKt.KeysignScreen (KeysignScreen.kt:39)
    at com.vultisig.wallet.ui.navigation.ComposableSingletons$NavGraphKt$lambda$-1950772210$1.invoke (NavGraph.kt:449)
    at com.vultisig.wallet.ui.navigation.ComposableSingletons$NavGraphKt$lambda$-1950772210$1.invoke (NavGraph.kt:447)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:142)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.navigation.compose.NavHostKt$NavHost$32$1.invoke (NavHost.kt:704)
    at androidx.navigation.compose.NavHostKt$NavHost$32$1.invoke (NavHost.kt:703)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:370)
    at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider (SaveableStateHolder.kt:82)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider (NavBackStackEntryProvider.kt:65)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider (NavBackStackEntryProvider.kt:1)
    at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke (NavBackStackEntryProvider.kt:52)
    at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke (NavBackStackEntryProvider.kt:51)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:370)
    at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider (NavBackStackEntryProvider.kt:47)
    at androidx.navigation.compose.NavHostKt$NavHost$32.invoke (NavHost.kt:703)
    at androidx.navigation.compose.NavHostKt$NavHost$32.invoke (NavHost.kt:683)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:142)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke (AnimatedContent.kt:863)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke (AnimatedContent.kt:853)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:130)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl (AnimatedVisibility.kt:752)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke (AnimatedContent.kt:835)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke (AnimatedContent.kt:818)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:51)
    at androidx.compose.animation.AnimatedContentKt.AnimatedContent (AnimatedContent.kt:873)
    at androidx.navigation.compose.NavHostKt.NavHost (NavHost.kt:655)
    at androidx.navigation.compose.NavHostKt.NavHost (NavHost.kt:356)
    at com.vultisig.wallet.ui.navigation.NavGraphKt.SetupNavGraph (NavGraph.kt:139)
    at com.vultisig.wallet.app.activity.components.MainActivityContentKt.MainActivityContent (MainActivityContent.kt:49)
    at com.vultisig.wallet.app.activity.MainActivity$onCreate$1$1.invoke (MainActivity.kt:83)
    at com.vultisig.wallet.app.activity.MainActivity$onCreate$1$1.invoke (MainActivity.kt:57)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.kt:121)
    at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke (ComposableLambda.kt:122)
    at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke (ComposableLambda.kt:122)
    at androidx.compose.runtime.RecomposeScopeImpl.compose (RecomposeScopeImpl.java:196)
    at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd (Composer.kt:2895)
    at androidx.compose.runtime.ComposerImpl.skipCurrentGroup (Composer.kt:3231)
    at androidx.compose.runtime.ComposerImpl.doCompose-aFTiNEg (Composer.kt:3855)
    at androidx.compose.runtime.ComposerImpl.recompose-aFTiNEg$runtime (ComposerImpl.java:3779)
    at androidx.compose.runtime.CompositionImpl.recompose (Composition.kt:1075)
    at androidx.compose.runtime.Recomposer.performRecompose (Recomposer.kt:1373)
    at androidx.compose.runtime.Recomposer.access$performRecompose (Recomposer.kt:156)
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend$lambda$22 (Recomposer.java:627)
    at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame (AndroidUiFrameClock.android.kt:39)
    at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch (AndroidUiDispatcher.java:108)
    at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch (AndroidUiDispatcher.java:41)
    at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame (AndroidUiDispatcher.android.kt:69)
    at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1688)
    at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1699)
    at android.view.Choreographer.doCallbacks (Choreographer.java:1154)
    at android.view.Choreographer.doFrame (Choreographer.java:1070)
    at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1647)
    at android.os.Handler.handleCallback (Handler.java:958)
    at android.os.Handler.dispatchMessage (Handler.java:99)
    at android.os.Looper.loopOnce (Looper.java:230)
    at android.os.Looper.loop (Looper.java:319)
    at android.app.ActivityThread.main (ActivityThread.java:9063)
    at java.lang.reflect.Method.invoke (Native method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:588)
    at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1103)
"ReferenceQueueDaemon" tid=5 Waiting
    at java.lang.Object.wait (Native method)
    at java.lang.Object.wait (Object.java:405)
    at java.lang.Object.wait (Object.java:543)
    at java.lang.Daemons$ReferenceQueueDaemon.runInternal (Daemons.java:262)
    at java.lang.Daemons$Daemon.run (Daemons.java:135)
    at java.lang.Thread.run (Thread.java:1563)
"FinalizerDaemon" tid=7 Waiting
    at java.lang.Object.wait (Native method)
    at java.lang.Object.wait (Object.java:405)
    at java.lang.ref.ReferenceQueue.remove (ReferenceQueue.java:207)
    at java.lang.ref.ReferenceQueue.remove (ReferenceQueue.java:228)
    at java.lang.Daemons$FinalizerDaemon.runInternal (Daemons.java:350)
    at java.lang.Daemons$Daemon.run (Daemons.java:135)
    at java.lang.Thread.run (Thread.java:1563)
"FinalizerWatchdogDaemon" tid=8 Timed Waiting
    at java.lang.Thread.sleep (Native method)
    at java.lang.Thread.sleep0 (Thread.java:681)
    at java.lang.Thread.sleep (Thread.java:659)
    at java.lang.Thread.sleep (Thread.java:572)
    at java.lang.Daemons$FinalizerWatchdogDaemon.sleepForNanos (Daemons.java:536)
    at java.lang.Daemons$FinalizerWatchdogDaemon.waitForProgress (Daemons.java:612)
    at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal (Daemons.java:467)
    at java.lang.Daemons$Daemon.run (Daemons.java:135)
    at java.lang.Thread.run (Thread.java:1563)
"OkHttp rpc.ninerealms.com" tid=34 Native
    #00  pc 0x00000000000e9328  /apex/com.android.runtime/lib64/bionic/libc.so (recvfrom+8)
    #01  pc 0x000000000002c4f8  /apex/com.android.art/lib64/libopenjdk.so (NET_Read+80)
    #02  pc 0x000000000002d074  /apex/com.android.art/lib64/libopenjdk.so (SocketInputStream_socketRead0+216)
    at java.net.SocketInputStream.socketRead0 (Native method)
    at java.net.SocketInputStream.socketRead (SocketInputStream.java:118)
    at java.net.SocketInputStream.read (SocketInputStream.java:173)
    at java.net.SocketInputStream.read (SocketInputStream.java:143)
    at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket (ConscryptEngineSocket.java:994)
    at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket (ConscryptEngineSocket.java:958)
    at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable (ConscryptEngineSocket.java:873)
    at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read (ConscryptEngineSocket.java:846)
    at okio.InputStreamSource.read (InputStreamSource.java:93)
    at okio.AsyncTimeout$source$1.read (AsyncTimeout.kt:153)
    at okio.RealBufferedSource.request (RealBufferedSource.kt:211)
    at okio.RealBufferedSource.require (RealBufferedSource.kt)
    at okhttp3.internal.http2.Http2Reader.nextFrame (Http2Reader.kt:89)
    at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke (Http2Connection.kt:618)
    at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke (Http2Connection.kt:609)
    at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce (TaskQueue.kt:98)
    at okhttp3.internal.concurrent.TaskRunner.runTask (TaskRunner.kt:116)
    at okhttp3.internal.concurrent.TaskRunner.access$runTask (TaskRunner.kt)
    at okhttp3.internal.concurrent.TaskRunner$runnable$1.run (TaskRunner.kt:65)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1154)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:652)
    at java.lang.Thread.run (Thread.java:1563)
"OkHttp TaskRunner" tid=36 Timed Waiting
    at java.lang.Object.wait (Native method)
    at okhttp3.internal.concurrent.TaskRunner$RealBackend.coordinatorWait (TaskRunner.kt:294)
    at okhttp3.internal.concurrent.TaskRunner.awaitTaskToRun (TaskRunner.kt:218)
    at okhttp3.internal.concurrent.TaskRunner$runnable$1.run (TaskRunner.kt:59)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1154)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:652)
    at java.lang.Thread.run (Thread.java:1563)
"Signal Catcher" tid=2 Runnable
    #00  pc 0x00000000004d57a4  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack+112)
    #01  pc 0x00000000004dadb4  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack const+204)
    #02  pc 0x00000000004dab9c  /apex/com.android.art/lib64/libart.so (art::DumpCheckpoint::Run+128)
    #03  pc 0x0000000000283d48  /apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint+2652)
    #04  pc 0x00000000004d9e08  /apex/com.android.art/lib64/libart.so (art::ThreadList::Dump+240)
    #05  pc 0x00000000004d984c  /apex/com.android.art/lib64/libart.so (art::ThreadList::DumpForSigQuit+392)
    #06  pc 0x00000000004d8738  /apex/com.android.art/lib64/libart.so (art::Runtime::DumpForSigQuit+52)
    #07  pc 0x00000000005455f4  /apex/com.android.art/lib64/libart.so (art::SignalCatcher::HandleSigQuit+640)
    #08  pc 0x00000000004bc5b8  /apex/com.android.art/lib64/libart.so (art::SignalCatcher::Run+1436)
    #09  pc 0x00000000000fd254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208)
    #10  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
"perfetto_hprof_listener" tid=3 Native
    #00  pc 0x00000000000e84a8  /apex/com.android.runtime/lib64/bionic/libc.so (read+8)
    #01  pc 0x000000000002d870  /apex/com.android.art/lib64/libperfetto_hprof.so (void* std::__1::__thread_proxy[abi:nn210000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, ArtPlugin_Initialize::$_7>>+316)
    #02  pc 0x00000000000fd254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208)
    #03  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
"Jit thread pool worker thread 0" tid=4 Native
    #00  pc 0x00000000000911c0  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32)
    #01  pc 0x0000000000201434  /apex/com.android.art/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks+136)
    #02  pc 0x00000000004722e8  /apex/com.android.art/lib64/libart.so (art::ThreadPoolWorker::Run+224)
    #03  pc 0x00000000004bd180  /apex/com.android.art/lib64/libart.so (art::ThreadPoolWorker::Callback+256)
    #04  pc 0x00000000000fd254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208)
    #05  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
"HeapTaskDaemon" tid=6 Waiting
    #00  pc 0x00000000000911c4  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+36)
    #01  pc 0x000000000024f624  /apex/com.android.art/lib64/libart.so (art::ConditionVariable::TimedWait+300)
    #02  pc 0x000000000024e8fc  /apex/com.android.art/lib64/libart.so (art::gc::TaskProcessor::RunAllTasks+216)
    at dalvik.system.VMRuntime.runHeapTasks (Native method)
    at java.lang.Daemons$HeapTaskDaemon.runInternal (Daemons.java:766)
    at java.lang.Daemons$Daemon.run (Daemons.java:135)
    at java.lang.Thread.run (Thread.java:1563)
"binder:16390_1" tid=9 Native
    #00  pc 0x00000000000e87cc  /apex/com.android.runtime/lib64/bionic/libc.so (__ioctl+12)
    #01  pc 0x000000000009f494  /apex/com.android.runtime/lib64/bionic/libc.so (ioctl+160)
    #02  pc 0x00000000000603ec  /system/lib64/libbinder.so (android::IPCThreadState::talkWithDriver+284)
    #03  pc 0x0000000000060734  /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand+28)
    #04  pc 0x0000000000061130  /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool+116)
    #05  pc 0x000000000006af14  /system/lib64/libbinder.so (android::PoolThread::threadLoop+132)
    #06  pc 0x00000000000142d4  /system/lib64/libutils.so (android::Thread::_threadLoop+288)
    #07  pc 0x00000000000f1934  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell+144)
    #08  pc 0x00000000000fd254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208)
    #09  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
"binder:16390_2" tid=10 Native
    #00  pc 0x00000000000e87cc  /apex/com.android.runtime/lib64/bionic/libc.so (__ioctl+12)
    #01  pc 0x000000000009f494  /apex/com.android.runtime/lib64/bionic/libc.so (ioctl+160)
    #02  pc 0x00000000000603ec  /system/lib64/libbinder.so (android::IPCThreadState::talkWithDriver+284)
    #03  pc 0x0000000000060734  /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand+28)
    #04  pc 0x0000000000061130  /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool+116)
    #05  pc 0x000000000006af14  /system/lib64/libbinder.so (android::PoolThread::threadLoop+132)
    #06  pc 0x00000000000142d4  /system/lib64/libutils.so (android::Thread::_threadLoop+288)
    #07  pc 0x00000000000f1934  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell+144)
    #08  pc 0x00000000000fd254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208)
    #09  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
"binder:16390_3" tid=11 Native
    #00  pc 0x00000000000e87cc  /apex/com.android.runtime/lib64/bionic/libc.so (__ioctl+12)
    #01  pc 0x000000000009f494  /apex/com.android.runtime/lib64/bionic/libc.so (ioctl+160)
    #02  pc 0x00000000000603ec  /system/lib64/libbinder.so (android::IPCThreadState::talkWithDriver+284)
    #03  pc 0x0000000000060734  /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand+28)
    #04  pc 0x0000000000061130  /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool+116)
    #05  pc 0x000000000006af14  /system/lib64/libbinder.so (android::PoolThread::threadLoop+132)
    #06  pc 0x00000000000142d4  /system/lib64/libutils.so (android::Thread::_threadLoop+288)
    #07  pc 0x00000000000f1934  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell+144)
    #08  pc 0x00000000000fd254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208)
    #09  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
"binder:16390_4" tid=12 Native
    #00  pc 0x00000000000e87cc  /apex/com.android.runtime/lib64/bionic/libc.so (__ioctl+12)
    #01  pc 0x000000000009f494  /apex/com.android.runtime/lib64/bionic/libc.so (ioctl+160)
    #02  pc 0x00000000000603ec  /system/lib64/libbinder.so (android::IPCThreadState::talkWithDriver+284)
    #03  pc 0x0000000000060734  /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand+28)
    #04  pc 0x0000000000061130  /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool+116)
    #05  pc 0x000000000006af14  /system/lib64/libbinder.so (android::PoolThread::threadLoop+132)
    #06  pc 0x00000000000142d4  /system/lib64/libutils.so (android::Thread::_threadLoop+288)
    #07  pc 0x00000000000f1934  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell+144)
    #08  pc 0x00000000000fd254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208)
    #09  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
"Profile Saver" tid=13 Native
    #00  pc 0x00000000000911c0  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32)
    #01  pc 0x0000000000201434  /apex/com.android.art/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks+136)
    #02  pc 0x00000000004bcbcc  /apex/com.android.art/lib64/libart.so (art::ProfileSaver::RunProfileSaverThread+364)
    #03  pc 0x00000000000fd254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208)
    #04  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
"queued-work-looper-data" tid=14 Waiting
    at jdk.internal.misc.Unsafe.park (Native method)
    at java.util.concurrent.locks.LockSupport.park (LockSupport.java:371)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block (AbstractQueuedSynchronizer.java:519)
    at java.util.concurrent.ForkJoinPool.unmanagedBlock (ForkJoinPool.java:3797)
    at java.util.concurrent.ForkJoinPool.managedBlock (ForkJoinPool.java:3738)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:1712)
    at java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:435)
    at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1080)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1140)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:652)
    at java.lang.Thread.run (Thread.java:1563)
"WM.task-1" tid=15 Waiting
    at jdk.internal.misc.Unsafe.park (Native method)
    at java.util.concurrent.locks.LockSupport.park (LockSupport.java:371)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block (AbstractQueuedSynchronizer.java:519)
    at java.util.concurrent.ForkJoinPool.unmanagedBlock (ForkJoinPool.java:3797)
    at java.util.concurrent.ForkJoinPool.managedBlock (ForkJoinPool.java:3738)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:1712)
    at java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:435)
    at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1080)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1140)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:652)
    at java.lang.Thread.run (Thread.java:1563)
"WM.task-2" tid=16 Waiting
    at jdk.internal.misc.Unsafe.park (Native method)
    at java.util.concurrent.locks.LockSupport.park (LockSupport.java:371)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block (AbstractQueuedSynchronizer.java:519)
    at java.util.concurrent.ForkJoinPool.unmanagedBlock (ForkJoinPool.java:3797)
    at java.util.concurrent.ForkJoinPool.managedBlock (ForkJoinPool.java:3738)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:1712)
    at java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:435)
    at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1080)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1140)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:652)
    at java.lang.Thread.run (Thread.java:1563)
"WM.task-3" tid=17 Waiting
    at jdk.internal.misc.Unsafe.park (Native method)
    at java.util.concurrent.locks.LockSupport.park (LockSupport.java:371)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block (AbstractQueuedSynchronizer.java:519)
    at java.util.concurrent.ForkJoinPool.unmanagedBlock (ForkJoinPool.java:3797)
    at java.util.concurrent.ForkJoinPool.managedBlock (ForkJoinPool.java:3738)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:1712)
    at java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:435)
    at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1080)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1140)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:652)
    at java.lang.Thread.run (Thread.java:1563)
"WM.task-4" tid=18 Waiting
    at jdk.internal.misc.Unsafe.park (Native method)
    at java.util.concurrent.locks.LockSupport.park (LockSupport.java:371)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block (AbstractQueuedSynchronizer.java:519)
    at java.util.concurrent.ForkJoinPool.unmanagedBlock (ForkJoinPool.java:3797)
    at java.util.concurrent.ForkJoinPool.managedBlock (ForkJoinPool.java:3738)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:1712)
    at java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:435)
    at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1080)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1140)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:652)
    at java.lang.Thread.run (Thread.java:1563)
"DefaultDispatcher-worker-1" tid=19 Timed Waiting
    at jdk.internal.misc.Unsafe.park (Native method)
    at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:410)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park (CoroutineScheduler.kt:855)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark (CoroutineScheduler.kt:803)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:751)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:704)
"DefaultDispatcher-worker-2" tid=20 Timed Waiting
    at jdk.internal.misc.Unsafe.park (Native method)
    at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:410)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park (CoroutineScheduler.kt:855)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark (CoroutineScheduler.kt:803)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:751)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:704)
"DefaultDispatcher-worker-3" tid=21 Timed Waiting
    at jdk.internal.misc.Unsafe.park (Native method)
    at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:410)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park (CoroutineScheduler.kt:855)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark (CoroutineScheduler.kt:803)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:751)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:704)
"RenderThread" tid=22 Native
    #00  pc 0x00000000000e978c  /apex/com.android.runtime/lib64/bionic/libc.so (__epoll_pwait+12)
    #01  pc 0x000000000001874c  /system/lib64/libutils.so (android::Looper::pollInner+192)
    #02  pc 0x0000000000018628  /system/lib64/libutils.so (android::Looper::pollOnce+124)
    #03  pc 0x0000000000529ec0  /system/lib64/libhwui.so (android::uirenderer::ThreadBase::waitForWork+164)
    #04  pc 0x000000000054dc84  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop+400)
    #05  pc 0x00000000000142d4  /system/lib64/libutils.so (android::Thread::_threadLoop+288)
    #06  pc 0x00000000000fd254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208)
    #07  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
"queued-work-looper-data" tid=23 Waiting
    at jdk.internal.misc.Unsafe.park (Native method)
    at java.util.concurrent.locks.LockSupport.park (LockSupport.java:371)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block (AbstractQueuedSynchronizer.java:519)
    at java.util.concurrent.ForkJoinPool.unmanagedBlock (ForkJoinPool.java:3797)
    at java.util.concurrent.ForkJoinPool.managedBlock (ForkJoinPool.java:3738)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:1712)
    at java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:435)
    at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1080)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1140)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:652)
    at java.lang.Thread.run (Thread.java:1563)
"arch_disk_io_0" tid=24 Waiting
    at jdk.internal.misc.Unsafe.park (Native method)
    at java.util.concurrent.locks.LockSupport.park (LockSupport.java:371)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block (AbstractQueuedSynchronizer.java:519)
    at java.util.concurrent.ForkJoinPool.unmanagedBlock (ForkJoinPool.java:3797)
    at java.util.concurrent.ForkJoinPool.managedBlock (ForkJoinPool.java:3738)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:1712)
    at java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:435)
    at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1080)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1140)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:652)
    at java.lang.Thread.run (Thread.java:1563)
"DefaultDispatcher-worker-4" tid=25 Timed Waiting
    at jdk.internal.misc.Unsafe.park (Native method)
    at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:410)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park (CoroutineScheduler.kt:855)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark (CoroutineScheduler.kt:803)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:751)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:704)
"DefaultDispatcher-worker-5" tid=26 Timed Waiting
    at jdk.internal.misc.Unsafe.park (Native method)
    at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:410)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park (CoroutineScheduler.kt:855)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark (CoroutineScheduler.kt:803)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:751)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:704)
"lottie-1-thread-1" tid=27 Timed Waiting
    at jdk.internal.misc.Unsafe.park (Native method)
    at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:410)
    at java.util.concurrent.LinkedTransferQueue$DualNode.await (LinkedTransferQueue.java:452)
    at java.util.concurrent.SynchronousQueue$Transferer.xferLifo (SynchronousQueue.java:194)
    at java.util.concurrent.SynchronousQueue.xfer (SynchronousQueue.java:235)
    at java.util.concurrent.SynchronousQueue.poll (SynchronousQueue.java:338)
    at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1079)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1140)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:652)
    at java.lang.Thread.run (Thread.java:1563)
"ConnectivityThread" tid=28 Native
    #00  pc 0x00000000000e978c  /apex/com.android.runtime/lib64/bionic/libc.so (__epoll_pwait+12)
    #01  pc 0x000000000001874c  /system/lib64/libutils.so (android::Looper::pollInner+192)
    #02  pc 0x0000000000018628  /system/lib64/libutils.so (android::Looper::pollOnce+124)
    #03  pc 0x00000000001904d0  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce+48)
    at android.os.MessageQueue.nativePollOnce (Native method)
    at android.os.MessageQueue.next (MessageQueue.java:335)
    at android.os.Looper.loopOnce (Looper.java:187)
    at android.os.Looper.loop (Looper.java:319)
    at android.os.HandlerThread.run (HandlerThread.java:67)
"SurfaceSyncGroupTimer" tid=29 Native
    #00  pc 0x00000000000e978c  /apex/com.android.runtime/lib64/bionic/libc.so (__epoll_pwait+12)
    #01  pc 0x000000000001874c  /system/lib64/libutils.so (android::Looper::pollInner+192)
    #02  pc 0x0000000000018628  /system/lib64/libutils.so (android::Looper::pollOnce+124)
    #03  pc 0x00000000001904d0  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce+48)
    at android.os.MessageQueue.nativePollOnce (Native method)
    at android.os.MessageQueue.next (MessageQueue.java:335)
    at android.os.Looper.loopOnce (Looper.java:187)
    at android.os.Looper.loop (Looper.java:319)
    at android.os.HandlerThread.run (HandlerThread.java:67)
"hwuiTask0" tid=30 Native
    #00  pc 0x00000000000911c0  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32)
    #01  pc 0x0000000000095f20  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex+148)
    #02  pc 0x00000000000fc4d4  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_cond_wait+80)
    #03  pc 0x000000000005d060  /system/lib64/libc++.so (std::__1::condition_variable::wait+24)
    #04  pc 0x0000000000551d98  /system/lib64/libhwui.so (android::uirenderer::CommonPool::workerLoop+112)
    #05  pc 0x0000000000551fd8  /system/lib64/libhwui.so (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, android::uirenderer::CommonPool::CommonPool::$_0>>+208)
    #06  pc 0x00000000000fd254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208)
    #07  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
"hwuiTask1" tid=31 Native
    #00  pc 0x00000000000911c0  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32)
    #01  pc 0x0000000000095f20  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex+148)
    #02  pc 0x00000000000fc4d4  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_cond_wait+80)
    #03  pc 0x000000000005d060  /system/lib64/libc++.so (std::__1::condition_variable::wait+24)
    #04  pc 0x0000000000551d98  /system/lib64/libhwui.so (android::uirenderer::CommonPool::workerLoop+112)
    #05  pc 0x0000000000551fd8  /system/lib64/libhwui.so (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, android::uirenderer::CommonPool::CommonPool::$_0>>+208)
    #06  pc 0x00000000000fd254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208)
    #07  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
"OkHttp Dispatcher" tid=33 Timed Waiting
    at jdk.internal.misc.Unsafe.park (Native method)
    at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:410)
    at java.util.concurrent.LinkedTransferQueue$DualNode.await (LinkedTransferQueue.java:452)
    at java.util.concurrent.SynchronousQueue$Transferer.xferLifo (SynchronousQueue.java:194)
    at java.util.concurrent.SynchronousQueue.xfer (SynchronousQueue.java:235)
    at java.util.concurrent.SynchronousQueue.poll (SynchronousQueue.java:338)
    at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1079)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1140)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:652)
    at java.lang.Thread.run (Thread.java:1563)
"OkHttp TaskRunner" tid=35 Timed Waiting
    at jdk.internal.misc.Unsafe.park (Native method)
    at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:410)
    at java.util.concurrent.LinkedTransferQueue$DualNode.await (LinkedTransferQueue.java:452)
    at java.util.concurrent.SynchronousQueue$Transferer.xferLifo (SynchronousQueue.java:194)
    at java.util.concurrent.SynchronousQueue.xfer (SynchronousQueue.java:235)
    at java.util.concurrent.SynchronousQueue.poll (SynchronousQueue.java:338)
    at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1079)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1140)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:652)
    at java.lang.Thread.run (Thread.java:1563)
"Okio Watchdog" tid=37 Timed Waiting
    at jdk.internal.misc.Unsafe.park (Native method)
    at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:269)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:1852)
    at okio.AsyncTimeout$Companion.awaitTimeout (AsyncTimeout.kt:358)
    at okio.AsyncTimeout$Watchdog.run (AsyncTimeout.kt:211)
"OkHttp TaskRunner" tid=38 Timed Waiting
    at jdk.internal.misc.Unsafe.park (Native method)
    at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:410)
    at java.util.concurrent.LinkedTransferQueue$DualNode.await (LinkedTransferQueue.java:452)
    at java.util.concurrent.SynchronousQueue$Transferer.xferLifo (SynchronousQueue.java:194)
    at java.util.concurrent.SynchronousQueue.xfer (SynchronousQueue.java:235)
    at java.util.concurrent.SynchronousQueue.poll (SynchronousQueue.java:338)
    at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1079)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1140)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:652)
    at java.lang.Thread.run (Thread.java:1563)
"VsyncReceiver" tid=16430 Unknown
    #00  pc 0x00000000000e978c  /apex/com.android.runtime/lib64/bionic/libc.so (__epoll_pwait+12)
    #01  pc 0x000000000001874c  /system/lib64/libutils.so (android::Looper::pollInner+192)
    #02  pc 0x0000000000018628  /system/lib64/libutils.so (android::Looper::pollOnce+124)
    #03  pc 0x000000000001a184  /system/lib64/libandroid.so (ALooper_pollOnce+104)
    #04  pc 0x000000000000e48c  /system_ext/lib64/libpenguin_impl.so (android::looperThread+228)
    #05  pc 0x00000000000fd254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208)
    #06  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
"RenderThread" tid=16442 Unknown
    #00  pc 0x00000000000911c0  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32)
    #01  pc 0x0000000000095f20  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex+148)
    #02  pc 0x00000000000a3f04  /apex/com.android.runtime/lib64/bionic/libc.so (sem_wait+112)
    #03  pc 0x0000000000304a10  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!cad2e78a02755cb9d475cedb69732b!7b26bdd942!+96)
    #04  pc 0x00000000000fd254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208)
    #05  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
"RenderThread" tid=16444 Unknown
    #00  pc 0x00000000000911c0  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32)
    #01  pc 0x0000000000095f20  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex+148)
    #02  pc 0x00000000000a3f04  /apex/com.android.runtime/lib64/bionic/libc.so (sem_wait+112)
    #03  pc 0x0000000000304a10  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!cad2e78a02755cb9d475cedb69732b!7b26bdd942!+96)
    #04  pc 0x00000000000fd254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208)
    #05  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
"RenderThread" tid=16445 Unknown
    #00  pc 0x00000000000911c0  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32)
    #01  pc 0x0000000000095f20  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex+148)
    #02  pc 0x00000000000a3f04  /apex/com.android.runtime/lib64/bionic/libc.so (sem_wait+112)
    #03  pc 0x0000000000304a10  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!cad2e78a02755cb9d475cedb69732b!7b26bdd942!+96)
    #04  pc 0x00000000000fd254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208)
    #05  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
"RenderThread" tid=16446 Unknown
    #00  pc 0x00000000000911c0  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32)
    #01  pc 0x0000000000095f20  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex+148)
    #02  pc 0x00000000000a3f04  /apex/com.android.runtime/lib64/bionic/libc.so (sem_wait+112)
    #03  pc 0x0000000000304a10  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!cad2e78a02755cb9d475cedb69732b!7b26bdd942!+96)
    #04  pc 0x00000000000fd254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208)
    #05  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
"RenderThread" tid=16447 Unknown
    #00  pc 0x00000000000911c0  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32)
    #01  pc 0x0000000000095f20  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex+148)
    #02  pc 0x00000000000a3f04  /apex/com.android.runtime/lib64/bionic/libc.so (sem_wait+112)
    #03  pc 0x0000000000304a10  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!cad2e78a02755cb9d475cedb69732b!7b26bdd942!+96)
    #04  pc 0x00000000000fd254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208)
    #05  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
"binder:16390_1" tid=16450 Unknown
    #00  pc 0x00000000000911c0  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32)
    #01  pc 0x0000000000095f20  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex+148)
    #02  pc 0x00000000000fc4d4  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_cond_wait+80)
    #03  pc 0x000000000005d060  /system/lib64/libc++.so (std::__1::condition_variable::wait+24)
    #04  pc 0x00000000000bd238  /system/lib64/libgui.so (android::AsyncWorker::run+140)
    #05  pc 0x00000000000bd624  /system/lib64/libgui.so (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void , android::AsyncWorker*>>+64)
    #06  pc 0x00000000000fd254  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208)
    #07  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)

```

### PR DESCRIPTION
**Pull request by aminsato**
https://orb.helius.dev/tx/2vmj2uRiRRvC8UVa1Xh4dzAgMLL59o4DFob33iAdsD7voA6BhrjyhDSNPyfg2XQu7PGBeHYNKGxBT1hXf3PWqcRX

## Description

Please include a summary of the change and which issue is fixed. 

Fixes #3217

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **New Features**
  * UI now exposes vault, amounts, destination, swap flag, QR image, and loading state for clearer on-screen feedback.
* **Refactor**
  * Screens and peer-discovery now consume a unified shared UI state, simplifying composition and QR/share visuals.
  * Keysign screen and navigation no longer require a transaction identifier at the public call site.
* **Bug Fixes**
  * Transaction-loading functions are now asynchronous to avoid blocking the UI and improve responsiveness.

### CODE REVIEW

File: app/src/main/java/com/vultisig/wallet/ui/models/keysign/KeysignShareViewModel.kt [hunk 1]
```diff
@@ -80,7 +79,7 @@ internal class KeysignShareViewModel @Inject constructor(
             this@KeysignShareViewModel.vault = vault
             amount.value = mapTokenValueToStringWithUnit(transaction.tokenValue)
             customMessagePayload = null
-            keysignPayload = KeysignPayload(
+            keysignPayload = KeysignPayload( // wrong data
```
Comment (johnnyluo) [inline app/src/main/java/com/vultisig/wallet/ui/models/keysign/KeysignShareViewModel.kt]: @aminsato why "wrong data"?
