### PR TITLE
fix: use simulated safe gas budget for Sui signing (#3988)

### LINKED ISSUE #3988: Sui signing ignores simulated safe gas budget, uses hardcoded default
## Description

`BlockChainSpecificRepository` hardcodes `gasBudget = SUI_DEFAULT_GAS_BUDGET` at line 477 instead of using the computed `finalSafeGasBudget` from `SuiFeeService`.

**File:** `data/src/main/kotlin/com/vultisig/wallet/data/repositories/BlockChainSpecificRepository.kt:469-478`
**Also see:** `data/src/main/kotlin/com/vultisig/wallet/data/blockchain/sui/SuiFeeService.kt:65-83`

## Impact

The signed transaction payload is built with the wrong gas budget. This is not just a UI estimate mismatch — the actual on-chain transaction uses the hardcoded value.

## Expected Behavior

Use the `finalSafeGasBudget` computed by `SuiFeeService` instead of `SUI_DEFAULT_GAS_BUDGET`.

### PR DESCRIPTION
**Pull request by aminsato**
## Summary

Closes #3988.

`BlockChainSpecificRepositoryImpl` hardcoded `gasBudget = SUI_DEFAULT_GAS_BUDGET` when building `BlockChainSpecific.Sui`, even though `SuiFeeService` already computes a safer budget via an on-chain dry-run (`computationCost + storageCost`, +15% margin, floored at `MIN_NETWORK_GAS_BUDGET = 2000`). Because this struct flows all the way into `SuiHelper.getPreSignedInputData(...).setGasBudget(...)`, the **on-chain** transaction was signed with the wrong budget — not a UI-only estimate mismatch.

## Changes

- `data/.../repositories/BlockChainSpecificRepository.kt` — the `TokenStandard.SUI` branch now calls `feeServiceComposite.calculateFees(Transfer(...))`, which routes to `SuiFeeService` and returns `GasFees(price, limit = finalSafeGasBudget, amount)`. `gasBudget` in `BlockChainSpecific.Sui` is set from `fees.limit`.
- Pattern matches the existing EVM branch (parallel `async` deferreds, `when (fees)` with an `error()` fallback for unsupported types).
- Removed the now-unused `SUI_DEFAULT_GAS_BUDGET` import.
- If the dry-run fails, `FeeServiceComposite` falls back to `SuiFeeService.calculateDefaultFees`, which still returns `GasFees` (with `SUI_DEFAULT_GAS_BUDGET * 1.15`) — safe for the runtime cast.

## Test plan

- [x] `./gradlew :data:compileDebugKotlin` — passes
- [x] `./gradlew :data:testDebugUnitTest --tests "*BlockChainSpecificRepositoryImplTest*"` — passes
- [x] `./gradlew ktfmtFormat` — applied
- [ ] Manual: send native SUI from a fragmented vault; verify the signed tx uses the simulated budget (not 3,000,000) and lands on-chain
- [ ] Manual: send a non-native SUI coin (Pay path); verify the gas coin selection + budget behave as before

Co-Authored-By: aminsato <Amin.saradar@yahoo.com>
Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>

## Summary by CodeRabbit

* **Bug Fixes**
  * SUI transactions now use dynamic fee estimation with explicit fallbacks, clearer error handling, and logging to improve reliability and fee accuracy.
* **Tests**
  * Added comprehensive SUI tests for successful estimation, estimator failures, cancellation behavior, unexpected fee types, and default-fallbacks.
  * Improved a UI test to await account-open state to avoid race conditions when asserting success.

### CODE REVIEW

File: data/src/main/kotlin/com/vultisig/wallet/data/repositories/BlockChainSpecificRepository.kt [hunk 1]
```diff
@@ -470,11 +469,30 @@ constructor(
...
+                        )
+                    }
+
+                    val safeGasBudget =
+                        when (val fees = feesDeferred.await()) {
+                            is GasFees -> fees.limit
+                            else ->
+                                error(
+                                    "Unsupported fee type ${fees::class.simpleName} for chain=$chain"
+                                )
```
Comment (rkokhatskyi) [inline data/src/main/kotlin/com/vultisig/wallet/data/repositories/BlockChainSpecificRepository.kt]: Failed network requests result to a wrong error, please handle it properly. Also this whole logic needs to be covered by tests

**Review by rkokhatskyi — DISMISSED** [review]
@aminsato please also attach tx link done for both fast vault, co-sign (secure vault). This needs to be tested on multiple co-sign options

File: data/src/main/kotlin/com/vultisig/wallet/data/repositories/BlockChainSpecificRepository.kt (hunk 1 above)
Comment (aminsato) [reply data/src/main/kotlin/com/vultisig/wallet/data/repositories/BlockChainSpecificRepository.kt]: Done

**Comment by aminsato** [comment]
> @aminsato please also attach tx link done for both fast vault, co-sign (secure vault). This needs to be tested on multiple co-sign options

https://suiscan.xyz/mainnet/tx/E5YYcSEqFS8qidMAje7cE8zE9WTBuGT1xjNb8FrWEQX1

**Review by johnnyluo — APPROVED** [review]
LGTM

**Review by johnnyluo — APPROVED** [review]
LGTM
