### PR TITLE
Fix decoding a message from a dApp

### LINKED ISSUE #2803: [BUG] Keysigns from dApp are not getting decoded
**Describe the bug**
When co-signing transactions/messages from dApps, they are not getting decoded. Making it impossible for the user to verify what they are signing

**Expected behavior**
Decode everything that is coming from dApp and Extension

**Screenshots**

Image

**Smartphone (please complete the following information):**
 - Version latest

### PR DESCRIPTION
**Pull request by aminsato**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #2803

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **New Features**
  * Improved message handling: custom messages are now automatically normalized and decoded. Hex-encoded payloads (including optional 0x prefix) are converted to readable UTF-8 and trimmed of extraneous control characters; if decoding fails, the original message is preserved to avoid data loss.
  * Error conditions are now logged and handled gracefully to maintain message integrity.

### CODE REVIEW

File: data/src/main/kotlin/com/vultisig/wallet/data/common/StringExtensions.kt [hunk 1]
```diff
@@ -29,6 +30,37 @@ fun String.toByteStringOrHex(): ByteString {
...
+                .map { it.toInt(16).toByte() }
+                .toByteArray()
+            String(
+                bytes,
+                Charsets.UTF_8
+            ).replace(
+                // Remove leading/trailing control characters
+                "^\\p{C}+|\\p{C}+$".toRegex(),
+                ""
+            )
```
Comment (JaimeToca) [inline data/src/main/kotlin/com/vultisig/wallet/data/common/StringExtensions.kt]: @aminsato can you check the following functions and extension functions:

- String.toHexBytes() 
- Numeric.hexStringToByteArray()
- toHexString()

Probably you can reuse those
