### PR TITLE
Fix releasing  fast button

### LINKED ISSUE #2059: [IMPROVE] Fast sign button release before completing animation
- [ ]  When holding for paired sign on fast vault tx and releasing the button before animation completed, please cancel any process instead of forwarding the user to fast sign. Either one press for fast sign or complete animation on hold should advance the user to the next screen

### PR DESCRIPTION
**Pull request by aminsato**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #2059

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved the holdable button's responsiveness by refining the long press detection and resetting the progress animation promptly after release.

### CODE REVIEW

File: app/src/main/java/com/vultisig/wallet/ui/components/buttons/VsHoldableButton.kt [hunk 1]
```diff
@@ -64,7 +64,7 @@ fun VsHoldableButton(
                         val up = waitForUpOrCancellation()
 
                         if (up != null) {
-                            if (progress.value < 1f) onClick()
+                            if (progress.value < 0.5f) onClick()
```
Comment (JaimeToca) [inline app/src/main/java/com/vultisig/wallet/ui/components/buttons/VsHoldableButton.kt:67]: I am also thinking to actually get a reference of "scope.launch" and call `cancelAndJoin`. thoughts?

**Review by johnnyluo — APPROVED** [review]
LGTM
